
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "pa", "carper" : "5", "t" : "1", "f" : "o", "dt" : "08\/10\/2018", "ht" : "01:21:11", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "17286", "st" : "17286", "snt" : "0", "e" : "5497589", "ea" : "5497589", "ena" : "0", "c" : "4400611", "a" : "1096978", "tv" : "8801222", "vb" : "528388", "vn" : "1096248", "vp" : "0", "vv" : "7007044", "vl" : "0", "van" : "169542", "vnom" : "7007044", "cand" : [ 
{ "seq" : "5", "sqcand" : "140000621028", "n" : "400", "nm" : "SIDNEY ROSA", "cc" : "PSB", "nv" : "LUIS MENDES", "ns2" : "LUIS MENDES", "nv" : "JUNIOR DA CITROPAR", "ns1" : "JUNIOR DA CITROPAR", "e" : "n", "v" : "642299", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "140000621333", "n" : "151", "nm" : "JADER BARBALHO", "cc" : "MDB - MDB \/ PP \/ PRB \/ PR \/ PSC \/ PTB \/ PHS \/ PMB \/ PODE \/ DC \/ PTC \/ PATRI \/ PSD \/ AVANTE \/ PSL \/ PROS", "nv" : "HELENILSON PONTES", "ns1" : "HELENILSON PONTES", "nv" : "CHAMON", "ns2" : "CHAMON", "e" : "s", "v" : "1383306", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "140000604415", "n" : "500", "nm" : "URSULA VIDAL", "cc" : "PSOL - PSOL \/ PPL \/ PCB", "nv" : "ROSA DE OLIVEIRA", "ns2" : "ROSA DE OLIVEIRA", "nv" : "ARACELI", "ns1" : "ARACELI", "e" : "n", "v" : "585344", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "12", "sqcand" : "140000604468", "n" : "543", "nm" : "XAROPINHO DO POVO", "cc" : "PPL - PSOL \/ PPL \/ PCB", "nv" : "ASTROLABIO SANTOS", "ns2" : "ASTROLABIO SANTOS", "nv" : "LENY CAMPELO", "ns1" : "LENY CAMPELO", "e" : "n", "v" : "21996", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "140000627207", "n" : "651", "nm" : "PROFESSOR GERSON DOURAO", "cc" : "PC do B - PT \/ PC do B", "nv" : "CATARINA KATIA", "ns2" : "CATARINA KATIA", "nv" : "MARIA IRENE", "ns1" : "MARIA IRENE", "e" : "n", "v" : "126078", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "140000620972", "n" : "123", "nm" : "CORONEL OSMAR NASCIMENTO", "cc" : "PDT", "nv" : "HENRIQUE SOARES", "ns2" : "HENRIQUE SOARES", "nv" : "ZÉ CARLOS", "ns1" : "ZÉ CARLOS", "e" : "n", "v" : "324331", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "140000627201", "n" : "131", "nm" : "ZÉ GERALDO", "cc" : "PT - PT \/ PC do B", "nv" : "APARECIDA IGREJA", "ns2" : "APARECIDA IGREJA", "nv" : "LUCIA MACHADO", "ns1" : "LUCIA MACHADO", "e" : "n", "v" : "806654", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "14", "sqcand" : "140000605248", "n" : "777", "nm" : "WLAD", "cc" : "SOLIDARIEDADE", "nv" : "NEGA LUCIMAR", "ns1" : "NEGA LUCIMAR", "nv" : "ANGÊLO RAIOL", "ns2" : "ANGÊLO RAIOL", "e" : "n", "v" : "0", "vap" : "165986", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "3", "sqcand" : "140000610437", "n" : "456", "nm" : "FLEXA RIBEIRO", "cc" : "PSDB", "nv" : "DIRCEU", "ns1" : "DIRCEU", "nv" : "RAIMUNDO", "ns2" : "RAIMUNDO", "e" : "n", "v" : "1138377", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "140000604134", "n" : "161", "nm" : "BENEDITA DO AMARAL", "cc" : "PSTU", "nv" : "SILVIO RIBEIRO", "ns2" : "SILVIO RIBEIRO", "nv" : "GALENO", "ns1" : "GALENO", "e" : "n", "v" : "38183", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "13", "sqcand" : "140000627777", "n" : "407", "nm" : "PRADO SÁ", "cc" : "PSB", "nv" : "EDNALDO TEMBÉ", "ns1" : "EDNALDO TEMBÉ", "nv" : "VALCIR OEIRAS CARDEL", "ns2" : "VALCIR OEIRAS CARDEL", "e" : "n", "v" : "0", "vap" : "3556", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "7", "sqcand" : "140000627357", "n" : "434", "nm" : "JARBAS VASCONCELOS", "cc" : "PV", "nv" : "SAVANAS", "ns2" : "SAVANAS", "nv" : "PARACAMPO", "ns1" : "PARACAMPO", "e" : "n", "v" : "440597", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "140000621337", "n" : "200", "nm" : "ZEQUINHA MARINHO", "cc" : "PSC - MDB \/ PP \/ PRB \/ PR \/ PSC \/ PTB \/ PHS \/ PMB \/ PODE \/ DC \/ PTC \/ PATRI \/ PSD \/ AVANTE \/ PSL \/ PROS", "nv" : "ARLINDO SILVA", "ns1" : "ARLINDO SILVA", "nv" : "MARINHO CUNHA", "ns2" : "MARINHO CUNHA", "e" : "s", "v" : "1374956", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "140000620621", "n" : "444", "nm" : "BOGO", "cc" : "PRP", "nv" : "KEILON  COELHO", "ns2" : "KEILON  COELHO", "nv" : "FABIO MAIA", "ns1" : "FABIO MAIA", "e" : "n", "v" : "124923", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }