
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "am", "carper" : "5", "t" : "1", "f" : "o", "dt" : "08\/10\/2018", "ht" : "06:40:09", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "7017", "st" : "7017", "snt" : "0", "e" : "2427111", "ea" : "2427111", "ena" : "0", "c" : "1957418", "a" : "469693", "tv" : "3914836", "vb" : "212516", "vn" : "410084", "vp" : "0", "vv" : "3292236", "vl" : "0", "van" : "0", "vnom" : "3292236", "cand" : [ 
{ "seq" : "4", "sqcand" : "40000610064", "n" : "222", "nm" : "ALFREDO NASCIMENTO", "cc" : "PR - PDT \/ PRP \/ AVANTE \/ PP \/ PV \/ PR \/ SOLIDARIEDADE \/ PPS \/ PTB \/ PHS \/ PSL \/ PPL", "nv" : "ANTONIO BARRETO", "ns2" : "ANTONIO BARRETO", "nv" : "ALUISIO BRAGA", "ns1" : "ALUISIO BRAGA", "e" : "n", "v" : "569766", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "40000618261", "n" : "155", "nm" : "EDUARDO BRAGA", "cc" : "MDB", "nv" : "SANDRA BRAGA", "ns1" : "SANDRA BRAGA", "nv" : "MIGUEL BIANGO", "ns2" : "MIGUEL BIANGO", "e" : "s", "v" : "607286", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "40000627725", "n" : "656", "nm" : "VANESSA", "cc" : "PC do B - PC do B \/ PT", "nv" : "THIAGO MEDEIROS", "ns1" : "THIAGO MEDEIROS", "nv" : "JOANILSON MENDES", "ns2" : "JOANILSON MENDES", "e" : "n", "v" : "373948", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "40000610062", "n" : "123", "nm" : "HISSA ABRAHÃO", "cc" : "PDT - PDT \/ PRP \/ AVANTE \/ PP \/ PV \/ PR \/ SOLIDARIEDADE \/ PPS \/ PTB \/ PHS \/ PSL \/ PPL", "nv" : "MARCELO SALDANHA", "ns2" : "MARCELO SALDANHA", "nv" : "AFRÂNIO GOMES", "ns1" : "AFRÂNIO GOMES", "e" : "n", "v" : "282736", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "40000602401", "n" : "500", "nm" : "LUIZ FERNANDO SANTOS", "cc" : "PSOL", "nv" : "MARCIA MAMEDE", "ns1" : "MARCIA MAMEDE", "nv" : "ADILSON MAIA", "ns2" : "ADILSON MAIA", "e" : "n", "v" : "27488", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "40000610393", "n" : "180", "nm" : "LUIZ CASTRO", "cc" : "REDE - REDE \/ PRTB \/ PSC", "nv" : "PERSEVERANDO GARCIA", "ns2" : "PERSEVERANDO GARCIA", "nv" : "MURIEL SARAGOUSSI", "ns1" : "MURIEL SARAGOUSSI", "e" : "n", "v" : "581553", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "40000602419", "n" : "508", "nm" : "RONDINELY FONSECA", "cc" : "PSOL", "nv" : "ROSILANE ALMEIDA", "ns1" : "ROSILANE ALMEIDA", "nv" : "EDILSON PEREIRA", "ns2" : "EDILSON PEREIRA", "e" : "n", "v" : "14650", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "40000603706", "n" : "455", "nm" : "PLINIO VALERIO", "cc" : "PSDB - PSD \/ PSDB \/ DEM \/ PRB \/ PTC \/ PATRI", "nv" : "JACIRA SOUZA", "ns2" : "JACIRA SOUZA", "nv" : "CARLOS ALBERTO", "ns1" : "CARLOS ALBERTO", "e" : "s", "v" : "834809", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }