
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "ms", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "19:48:38", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "6529", "st" : "6529", "snt" : "0", "e" : "1876929", "ea" : "1876929", "ena" : "0", "c" : "1478642", "a" : "398287", "tv" : "2957284", "vb" : "242899", "vn" : "376942", "vp" : "0", "vv" : "2308521", "vl" : "0", "van" : "28922", "vnom" : "2308521", "cand" : [ 
{ "seq" : "4", "sqcand" : "120000606861", "n" : "456", "nm" : "MARCELO MIGLIOLI", "cc" : "PSDB - PMN \/ DEM \/ PP \/ PSB \/ PTB \/ PSDB \/ PATRI \/ PSD \/ PPS \/ AVANTE \/ SOLIDARIEDADE \/ PROS", "nv" : "DANIELA HALL", "ns2" : "DANIELA HALL", "nv" : "PASTOR DIONIZIO", "ns1" : "PASTOR DIONIZIO", "e" : "n", "v" : "347861", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "120000612741", "n" : "500", "nm" : "ANISIO GUATO", "cc" : "PSOL", "nv" : "CONCILIADOR MARCIO", "ns1" : "CONCILIADOR MARCIO", "nv" : "JACQUES", "ns2" : "JACQUES", "e" : "n", "v" : "28888", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "120000606866", "n" : "144", "nm" : "NELSINHO TRAD", "cc" : "PTB - PMN \/ DEM \/ PP \/ PSB \/ PTB \/ PSDB \/ PATRI \/ PSD \/ PPS \/ AVANTE \/ SOLIDARIEDADE \/ PROS", "nv" : "JOSÉ CHAGAS", "ns1" : "JOSÉ CHAGAS", "nv" : "PROFESSORA BAZÉ", "ns2" : "PROFESSORA BAZÉ", "e" : "s", "v" : "424085", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "13", "sqcand" : "120000627470", "n" : "543", "nm" : "THIAGO FREITAS", "cc" : "PPL", "nv" : "FERNANDO ALMEIDA", "ns2" : "FERNANDO ALMEIDA", "nv" : "PASTOR LUIZ", "ns1" : "PASTOR LUIZ", "e" : "n", "v" : "0", "vap" : "9520", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "11", "sqcand" : "120000603540", "n" : "356", "nm" : "BETINI", "cc" : "PMB", "nv" : "MEIRE XAVIER", "ns1" : "MEIRE XAVIER", "nv" : "GISLAINE ROCHA", "ns2" : "GISLAINE ROCHA", "e" : "n", "v" : "14415", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "120000605501", "n" : "654", "nm" : "MARIO  FONSECA", "cc" : "PC do B - REDE \/ PC do B \/ PV", "nv" : "LUCIANNE PINA", "ns2" : "LUCIANNE PINA", "nv" : "ELIAS CAMILO", "ns1" : "ELIAS CAMILO", "e" : "n", "v" : "30619", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "120000620261", "n" : "133", "nm" : "ZECA DO PT", "cc" : "PT", "nv" : "LAERTE TETILA", "ns1" : "LAERTE TETILA", "nv" : "GISELLE MARQUES", "ns2" : "GISELLE MARQUES", "e" : "n", "v" : "294059", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "12", "sqcand" : "120000603773", "n" : "190", "nm" : "BETO FIGUEIRÓ", "cc" : "PODE - PDT \/ PRB \/ PODE", "nv" : "HERBERT ASSUNÇÃO DE FREITAS", "ns1" : "HERBERT ASSUNÇÃO DE FREITAS", "nv" : "MARCO AURÉLIO", "ns2" : "MARCO AURÉLIO", "e" : "n", "v" : "0", "vap" : "19402", "dsit" : "Deferido", "svnom" : "s" }, 
{ "seq" : "8", "sqcand" : "120000628740", "n" : "100", "nm" : "GILMAR DA CRUZ", "cc" : "PRB - PDT \/ PRB \/ PODE", "nv" : "ANGELO MENDES", "ns2" : "ANGELO MENDES", "nv" : "JOSIAS DE CARVALHO", "ns1" : "JOSIAS DE CARVALHO", "e" : "n", "v" : "35227", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "120000624873", "n" : "151", "nm" : "MOKA", "cc" : "MDB - MDB \/ PR \/ DC \/ PRTB \/ PHS \/ PRP", "nv" : "MANO", "ns1" : "MANO", "nv" : "MARIA EMILIA", "ns2" : "MARIA EMILIA", "e" : "n", "v" : "357427", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "120000623873", "n" : "177", "nm" : "SORAYA THRONICKE", "cc" : "PSL", "nv" : "RODOLFO NOGUEIRA", "ns1" : "RODOLFO NOGUEIRA", "nv" : "DANNY FABRICIO", "ns2" : "DANNY FABRICIO", "e" : "s", "v" : "373712", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "120000627285", "n" : "200", "nm" : "PROMOTOR SERGIO HARFOUCHE", "cc" : "PSC", "nv" : "MACKSON VIANNA", "ns2" : "MACKSON VIANNA", "nv" : "EDSON ALMEIDA", "ns1" : "EDSON ALMEIDA", "e" : "n", "v" : "292301", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "120000630079", "n" : "368", "nm" : "DELCIDIO AMARAL", "cc" : "PTC", "nv" : "NIAGARA KRAIEVSKI", "ns2" : "NIAGARA KRAIEVSKI", "nv" : "GAZOLLA", "ns1" : "GAZOLLA", "e" : "n", "v" : "109927", "vap" : "0", "dsit" : "Pendente de julgamento", "svnom" : "n" } ] }