
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "pe", "carper" : "5", "t" : "1", "f" : "o", "dt" : "08\/10\/2018", "ht" : "00:01:06", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "19797", "st" : "19797", "snt" : "0", "e" : "6567535", "ea" : "6567535", "ena" : "0", "c" : "5391639", "a" : "1175896", "tv" : "10783278", "vb" : "1180640", "vn" : "2942712", "vp" : "0", "vv" : "6653095", "vl" : "0", "van" : "6831", "vnom" : "6653095", "cand" : [ 
{ "seq" : "7", "sqcand" : "170000607402", "n" : "500", "nm" : "ALBANISE", "cc" : "PSOL - PSOL \/ PCB", "nv" : "JACIRA GALVÃO", "ns1" : "JACIRA GALVÃO", "nv" : "NÁDIA GOMES", "ns2" : "NÁDIA GOMES", "e" : "n", "v" : "142280", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "170000617293", "n" : "700", "nm" : "SILVIO COSTA", "cc" : "AVANTE - PROS \/ AVANTE \/ PDT", "nv" : "RUY COUTINHO", "ns2" : "RUY COUTINHO", "nv" : "CARMINHA QUEIROZ", "ns1" : "CARMINHA QUEIROZ", "e" : "n", "v" : "680435", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "170000604548", "n" : "130", "nm" : "HUMBERTO COSTA", "cc" : "PT - PSB \/ PC do B \/ PT \/ MDB \/ PP \/ PR \/ PMN \/ PTC \/ PRP \/ PATRI \/ PSD \/ PPL \/ SOLIDARIEDADE", "nv" : "MARCIA DO ANGICO", "ns2" : "MARCIA DO ANGICO", "nv" : "WALDEMAR OLIVEIRA", "ns1" : "WALDEMAR OLIVEIRA", "e" : "s", "v" : "1713565", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "170000607380", "n" : "505", "nm" : "EUGÊNIA", "cc" : "PSOL - PSOL \/ PCB", "nv" : "HORTÊNSIA", "ns2" : "HORTÊNSIA", "nv" : "KATIA CUNHA", "ns1" : "KATIA CUNHA", "e" : "n", "v" : "113703", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "170000606878", "n" : "161", "nm" : "HELIO CABRAL", "cc" : "PSTU", "nv" : "PROFESSOR MARIANO", "ns1" : "PROFESSOR MARIANO", "nv" : "LOURDES FLORENTINO", "ns2" : "LOURDES FLORENTINO", "e" : "n", "v" : "16766", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "170000605130", "n" : "252", "nm" : "MENDONCA FILHO", "cc" : "DEM - PTB \/ PPS \/ PSDB \/ DEM \/ PSC \/ PRB \/ PV \/ PODE \/ PRTB \/ PSL \/ PHS \/ DC \/ PMB", "nv" : "JORGE CORTE REAL", "ns1" : "JORGE CORTE REAL", "nv" : "CORONEL JOSÉ ALVES", "ns2" : "CORONEL JOSÉ ALVES", "e" : "n", "v" : "1302446", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "170000617292", "n" : "900", "nm" : "LIDIA BRUNES", "cc" : "PROS - PROS \/ AVANTE \/ PDT", "nv" : "IVETE DA SILVA", "ns1" : "IVETE DA SILVA", "nv" : "MANA", "ns2" : "MANA", "e" : "n", "v" : "44727", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "12", "sqcand" : "170000624072", "n" : "290", "nm" : "ALEX LIMA ROLA", "cc" : "PCO", "nv" : "PABLO YURI", "ns2" : "PABLO YURI", "nv" : "UBIRACY OLIMPIO", "ns1" : "UBIRACY OLIMPIO", "e" : "n", "v" : "0", "vap" : "6831", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "4", "sqcand" : "170000605133", "n" : "456", "nm" : "BRUNO ARAUJO", "cc" : "PSDB - PTB \/ PPS \/ PSDB \/ DEM \/ PSC \/ PRB \/ PV \/ PODE \/ PRTB \/ PSL \/ PHS \/ DC \/ PMB", "nv" : "GUILHERME COELHO", "ns1" : "GUILHERME COELHO", "nv" : "BETINHA NASCIMENTO", "ns2" : "BETINHA NASCIMENTO", "e" : "n", "v" : "925371", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "170000627509", "n" : "188", "nm" : "ADRIANA ROCHA", "cc" : "REDE", "nv" : "ELNATAM BARROS DE LIMA", "ns1" : "ELNATAM BARROS DE LIMA", "nv" : "MIRTES CELESTINO", "ns2" : "MIRTES CELESTINO", "e" : "n", "v" : "91941", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "170000604551", "n" : "156", "nm" : "JARBAS", "cc" : "MDB - PSB \/ PC do B \/ PT \/ MDB \/ PP \/ PR \/ PMN \/ PTC \/ PRP \/ PATRI \/ PSD \/ PPL \/ SOLIDARIEDADE", "nv" : "ADILSON GOMES", "ns2" : "ADILSON GOMES", "nv" : "FERNANDO DUEIRE", "ns1" : "FERNANDO DUEIRE", "e" : "s", "v" : "1430802", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "170000627506", "n" : "180", "nm" : "PASTOR JAIRINHO", "cc" : "REDE", "nv" : "GETÚLIO CARDOSO", "ns1" : "GETÚLIO CARDOSO", "nv" : "ALESSANDRA SARAIVA", "ns2" : "ALESSANDRA SARAIVA", "e" : "n", "v" : "191059", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }