
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "rs", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "23:38:55", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "27274", "st" : "27274", "snt" : "0", "e" : "8350718", "ea" : "8350718", "ena" : "0", "c" : "6835866", "a" : "1514852", "tv" : "13671732", "vb" : "1547540", "vn" : "1565943", "vp" : "0", "vv" : "10556398", "vl" : "0", "van" : "1851", "vnom" : "10556398", "cand" : [ 
{ "seq" : "2", "sqcand" : "210000606445", "n" : "131", "nm" : "PAULO PAIM", "cc" : "PT - PT \/ PC do B", "nv" : "REGINETE BISPO", "ns2" : "REGINETE BISPO", "nv" : "CLEONICE BACK", "ns1" : "CLEONICE BACK", "e" : "s", "v" : "1875245", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "210000604671", "n" : "190", "nm" : "ANA VARELA", "cc" : "PODE - PDT \/ AVANTE \/ PV \/ PODE \/ PPL \/ PMB \/ SOLIDARIEDADE", "nv" : "JEAN CARISSIMI", "ns1" : "JEAN CARISSIMI", "nv" : "LUCIANO GOLDENBERG", "ns2" : "LUCIANO GOLDENBERG", "e" : "n", "v" : "101504", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "12", "sqcand" : "210000600029", "n" : "212", "nm" : "CLEBER SOARES", "cc" : "PCB - PSOL \/ PCB", "nv" : "JONH ELVIS", "ns1" : "JONH ELVIS", "nv" : "LEANDRO GONÇALVES", "ns2" : "LEANDRO GONÇALVES", "e" : "n", "v" : "23963", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "210000622364", "n" : "111", "nm" : "LUIS CARLOS HEINZE", "cc" : "PP - PSDB \/ PTB \/ PRB \/ PPS \/ PHS \/ REDE \/ PP", "nv" : "DRICA DE LUCENA", "ns2" : "DRICA DE LUCENA", "nv" : "IRENEU ORTH", "ns1" : "IRENEU ORTH", "e" : "s", "v" : "2316365", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "210000610051", "n" : "161", "nm" : "MARLI SCHAULE", "cc" : "PSTU", "nv" : "ROBERTO ROST", "ns1" : "ROBERTO ROST", "nv" : "JOSÉ GUILHERME", "ns2" : "JOSÉ GUILHERME", "e" : "n", "v" : "26242", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "210000606449", "n" : "651", "nm" : "ABIGAIL PEREIRA", "cc" : "PC do B - PT \/ PC do B", "nv" : "MÁRCIA LUCAS", "ns2" : "MÁRCIA LUCAS", "nv" : "EVERLEI MARTINS", "ns1" : "EVERLEI MARTINS", "e" : "n", "v" : "970286", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "210000600026", "n" : "500", "nm" : "ROMER GUEX", "cc" : "PSOL - PSOL \/ PCB", "nv" : "JOÃO EZEQUIEL", "ns1" : "JOÃO EZEQUIEL", "nv" : "OSMAR TONINI", "ns2" : "OSMAR TONINI", "e" : "n", "v" : "49023", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "210000604669", "n" : "777", "nm" : "DRA. SANDRA WEBER", "cc" : "SOLIDARIEDADE - PDT \/ AVANTE \/ PV \/ PODE \/ PPL \/ PMB \/ SOLIDARIEDADE", "nv" : "LANDO", "ns1" : "LANDO", "nv" : "CARLOS VARREIRA", "ns2" : "CARLOS VARREIRA", "e" : "n", "v" : "263411", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "210000606874", "n" : "151", "nm" : "JOSÉ FOGAÇA", "cc" : "MDB - MDB \/ PSD \/ PSB \/ PR \/ PSC \/ PATRI \/ PRP \/ PMN \/ PTC", "nv" : "ANA OLIVEIRA", "ns2" : "ANA OLIVEIRA", "nv" : "PASTOR PEDRO OLIVEIRA", "ns1" : "PASTOR PEDRO OLIVEIRA", "e" : "n", "v" : "1465700", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "210000622363", "n" : "234", "nm" : "MARIO BERND", "cc" : "PPS - PSDB \/ PTB \/ PRB \/ PPS \/ PHS \/ REDE \/ PP", "nv" : "MARLI IGLESIAS", "ns2" : "MARLI IGLESIAS", "nv" : "MICHELI PETRY", "ns1" : "MICHELI PETRY", "e" : "n", "v" : "233747", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "210000606869", "n" : "400", "nm" : "BETO ALBUQUERQUE", "cc" : "PSB - MDB \/ PSD \/ PSB \/ PR \/ PSC \/ PATRI \/ PRP \/ PMN \/ PTC", "nv" : "ADRIANE CERINI", "ns1" : "ADRIANE CERINI", "nv" : "DAIANE DIAS", "ns2" : "DAIANE DIAS", "e" : "n", "v" : "1713792", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "14", "sqcand" : "210000605578", "n" : "273", "nm" : "MACHADO", "cc" : "DC", "nv" : "GETULIO AMARAL", "ns2" : "GETULIO AMARAL", "nv" : "JOMAR", "ns1" : "JOMAR", "e" : "n", "v" : "0", "vap" : "15644", "dsit" : "Deferido", "svnom" : "s" }, 
{ "seq" : "15", "sqcand" : "210000623878", "n" : "290", "nm" : "LUIZ DELVAIR", "cc" : "PCO", "nv" : "EMERSON BROTTO", "ns1" : "EMERSON BROTTO", "nv" : "OSCAR DE SOUZA", "ns2" : "OSCAR DE SOUZA", "e" : "n", "v" : "0", "vap" : "1851", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "13", "sqcand" : "210000610053", "n" : "160", "nm" : "JOÃO AUGUSTO", "cc" : "PSTU", "nv" : "DENIOR", "ns2" : "DENIOR", "nv" : "LUIZ FERNANDO KIST", "ns1" : "LUIZ FERNANDO KIST", "e" : "n", "v" : "7963", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "210000603704", "n" : "170", "nm" : "CARMEN FLORES", "cc" : "PSL - DEM \/ PSL \/ PROS", "nv" : "EVANDRO SOARES", "ns1" : "EVANDRO SOARES", "nv" : "JESSE JAMES", "ns2" : "JESSE JAMES", "e" : "n", "v" : "1509157", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }