
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "ba", "carper" : "5", "t" : "1", "f" : "o", "dt" : "08\/10\/2018", "ht" : "03:02:08", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "31192", "st" : "31192", "snt" : "0", "e" : "10390247", "ea" : "10390247", "ena" : "0", "c" : "8235310", "a" : "2154937", "tv" : "16470620", "vb" : "1075280", "vn" : "3482999", "vp" : "1492", "vv" : "11910849", "vl" : "0", "van" : "0", "vnom" : "11910849", "cand" : [ 
{ "seq" : "8", "sqcand" : "50000623173", "n" : "188", "nm" : "FRANCISCO JOSÉ", "cc" : "REDE", "nv" : "ANA DALVA BATISTA REIS", "ns1" : "ANA DALVA BATISTA REIS", "nv" : "JOÃO GONÇALVES", "ns2" : "JOÃO GONÇALVES", "e" : "n", "v" : "44524", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "50000608313", "n" : "200", "nm" : "IRMÃO LÁZARO", "cc" : "PSC - DEM \/ PSDB \/ PSC \/ PTB \/ PRB \/ SOLIDARIEDADE \/ PV \/ PPL", "nv" : "ELIEL SANTANA", "ns2" : "ELIEL SANTANA", "nv" : "IVANILSON GOMES", "ns1" : "IVANILSON GOMES", "e" : "n", "v" : "1830581", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "50000622083", "n" : "280", "nm" : "CELSINHO COTRIM", "cc" : "PRTB - PRTB \/ PSL", "nv" : "ANDREI GOES", "ns1" : "ANDREI GOES", "nv" : "GILSON PRESÍDIO", "ns2" : "GILSON PRESÍDIO", "e" : "n", "v" : "41055", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "50000607716", "n" : "555", "nm" : "ANGELO CORONEL", "cc" : "PSD - PT \/ PP \/ PDT \/ PSD \/ PSB \/ PC do B \/ PR \/ PMB \/ PRP \/ PODE \/ AVANTE \/ PMN \/ PROS \/ PTC", "nv" : "DRA.SILVIA", "ns2" : "DRA.SILVIA", "nv" : "DAVIDSON MAGALHÃES", "ns1" : "DAVIDSON MAGALHÃES", "e" : "s", "v" : "3927598", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "50000618936", "n" : "290", "nm" : "ADROALDO DOS SANTOS", "cc" : "PCO", "nv" : "ALMIR CABRAL", "ns2" : "ALMIR CABRAL", "nv" : "VALDIR SANTOS", "ns1" : "VALDIR SANTOS", "e" : "n", "v" : "21182", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "50000622084", "n" : "170", "nm" : "COMANDANTE RANGEL", "cc" : "PSL - PRTB \/ PSL", "nv" : "VILSON COUTINHO QUINTA POINT", "ns2" : "VILSON COUTINHO QUINTA POINT", "nv" : "TENÓRIO FILHO", "ns1" : "TENÓRIO FILHO", "e" : "n", "v" : "577645", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "50000607712", "n" : "130", "nm" : "JAQUES WAGNER", "cc" : "PT - PT \/ PP \/ PDT \/ PSD \/ PSB \/ PC do B \/ PR \/ PMB \/ PRP \/ PODE \/ AVANTE \/ PMN \/ PROS \/ PTC", "nv" : "BEBETO", "ns1" : "BEBETO", "nv" : "LUCIANA LEÃO MUNIZ", "ns2" : "LUCIANA LEÃO MUNIZ", "e" : "s", "v" : "4253331", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "50000608057", "n" : "150", "nm" : "JORGE VIANNA", "cc" : "MDB - MDB \/ DC", "nv" : "JORGE RIOS", "ns1" : "JORGE RIOS", "nv" : "ALCEU BARROS", "ns2" : "ALCEU BARROS", "e" : "n", "v" : "60907", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "50000608315", "n" : "456", "nm" : "JUTAHY MAGALHAES JUNIOR", "cc" : "PSDB - DEM \/ PSDB \/ PSC \/ PTB \/ PRB \/ SOLIDARIEDADE \/ PV \/ PPL", "nv" : "EREMITA MOTA", "ns1" : "EREMITA MOTA", "nv" : "JULIO SANTOS", "ns2" : "JULIO SANTOS", "e" : "n", "v" : "948541", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "50000608112", "n" : "277", "nm" : "MARCOS MAURICIO", "cc" : "DC - MDB \/ DC", "nv" : "ANTONIO ALBINO", "ns2" : "ANTONIO ALBINO", "nv" : "MARCELO BARRETO", "ns1" : "MARCELO BARRETO", "e" : "n", "v" : "39780", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "50000600866", "n" : "500", "nm" : "FABIO NOGUEIRA", "cc" : "PSOL", "nv" : "BERNADETE SOUZA", "ns1" : "BERNADETE SOUZA", "nv" : "KLEBER ROSA", "ns2" : "KLEBER ROSA", "e" : "n", "v" : "165705", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }