
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "sc", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "21:04:49", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "15562", "st" : "15562", "snt" : "0", "e" : "5068421", "ea" : "5068421", "ena" : "0", "c" : "4241667", "a" : "826754", "tv" : "8483334", "vb" : "772905", "vn" : "1172937", "vp" : "0", "vv" : "6530439", "vl" : "0", "van" : "7053", "vnom" : "6530439", "cand" : [ 
{ "seq" : "9", "sqcand" : "240000616320", "n" : "181", "nm" : "MIRIAM PROCHNOW", "cc" : "REDE", "nv" : "NELSON ZUNINO", "ns1" : "NELSON ZUNINO", "nv" : "MARIA MARGARETE CECCONI", "ns2" : "MARIA MARGARETE CECCONI", "e" : "n", "v" : "84486", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "240000624344", "n" : "131", "nm" : "LÉDIO ROSA", "cc" : "PT", "nv" : "IRIO CORRÊA", "ns2" : "IRIO CORRÊA", "nv" : "VANIO DOS SANTOS", "ns1" : "VANIO DOS SANTOS", "e" : "n", "v" : "327226", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "240000609536", "n" : "456", "nm" : "PAULO BAUER", "cc" : "PSDB - MDB \/ AVANTE \/ PSDB \/ PTB \/ PTC \/ PRTB \/ DC \/ PR \/ PPS", "nv" : "CASILDO MALDANER", "ns1" : "CASILDO MALDANER", "nv" : "SANDRO GIASSI SERAFIM", "ns2" : "SANDRO GIASSI SERAFIM", "e" : "n", "v" : "802037", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "240000614221", "n" : "331", "nm" : "ROBERTO SALUM", "cc" : "PMN - PMN \/ PATRI", "nv" : "AIRTON ZANELLA", "ns1" : "AIRTON ZANELLA", "nv" : "AILSON BARROSO", "ns2" : "AILSON BARROSO", "e" : "n", "v" : "246686", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "240000609726", "n" : "177", "nm" : "LUCAS ESMERALDINO", "cc" : "PSL", "nv" : "MARCELO BRIGADEIRO", "ns1" : "MARCELO BRIGADEIRO", "nv" : "DR MARCO", "ns2" : "DR MARCO", "e" : "n", "v" : "1161662", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "240000609539", "n" : "222", "nm" : "JORGINHO MELLO", "cc" : "PR - MDB \/ AVANTE \/ PSDB \/ PTB \/ PTC \/ PRTB \/ DC \/ PR \/ PPS", "nv" : "IVETE DA SILVEIRA", "ns1" : "IVETE DA SILVEIRA", "nv" : "BETO MARTINS", "ns2" : "BETO MARTINS", "e" : "s", "v" : "1179757", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "12", "sqcand" : "240000616323", "n" : "188", "nm" : "DIEGO MEZZOGIORNO", "cc" : "REDE", "nv" : "HELI SCHLICKMANN", "ns1" : "HELI SCHLICKMANN", "nv" : "ALEXANDRE LEMOS", "ns2" : "ALEXANDRE LEMOS", "e" : "n", "v" : "38470", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "240000624339", "n" : "130", "nm" : "IDELI SALVATTI", "cc" : "PT", "nv" : "MARILUCI", "ns1" : "MARILUCI", "nv" : "RICARDO PELEGRINELLO", "ns2" : "RICARDO PELEGRINELLO", "e" : "n", "v" : "336449", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "240000601867", "n" : "500", "nm" : "PROFESSOR PEDRO CABRAL", "cc" : "PSOL - PSOL \/ PCB", "nv" : "FRANCISCO CORDEIRO", "ns1" : "FRANCISCO CORDEIRO", "nv" : "ADEMIR KUHN", "ns2" : "ADEMIR KUHN", "e" : "n", "v" : "63523", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "240000601872", "n" : "505", "nm" : "PROFESSOR ANTONIO", "cc" : "PSOL - PSOL \/ PCB", "nv" : "ROBSON CERON", "ns1" : "ROBSON CERON", "nv" : "DILENE", "ns2" : "DILENE", "e" : "n", "v" : "51191", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "240000621326", "n" : "111", "nm" : "ESPERIDIÃO AMIN", "cc" : "PP - PSD \/ PRB \/ PDT \/ PSB \/ PODE \/ SOLIDARIEDADE \/ PROS \/ PSC \/ PC do B \/ PHS \/ PP \/ DEM \/ PRP \/ PPL \/ PV", "nv" : "GERALDO ALTHOFF", "ns1" : "GERALDO ALTHOFF", "nv" : "DENISE DOS SANTOS", "ns2" : "DENISE DOS SANTOS", "e" : "s", "v" : "1226064", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "14", "sqcand" : "240000617002", "n" : "290", "nm" : "ANDREÁ LUCIANO CARVALHO", "cc" : "PCO", "nv" : "MARINA NIENOW DE BARROS", "ns1" : "MARINA NIENOW DE BARROS", "nv" : "RONALDO LOUREIRO", "ns2" : "RONALDO LOUREIRO", "e" : "n", "v" : "0", "vap" : "7053", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "13", "sqcand" : "240000610040", "n" : "160", "nm" : "RICARDO LAUTERT", "cc" : "PSTU", "nv" : "PROFESSOR ROQUE", "ns1" : "PROFESSOR ROQUE", "nv" : "PEDRO ROGEL ", "ns2" : "PEDRO ROGEL ", "e" : "n", "v" : "13845", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "240000621322", "n" : "555", "nm" : "RAIMUNDO COLOMBO", "cc" : "PSD - PSD \/ PRB \/ PDT \/ PSB \/ PODE \/ SOLIDARIEDADE \/ PROS \/ PSC \/ PC do B \/ PHS \/ PP \/ DEM \/ PRP \/ PPL \/ PV", "nv" : "NARCIZO PARISOTTO", "ns2" : "NARCIZO PARISOTTO", "nv" : "JANDIR BELLINI", "ns1" : "JANDIR BELLINI", "e" : "n", "v" : "999043", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }