
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "ce", "carper" : "5", "t" : "1", "f" : "o", "dt" : "08\/10\/2018", "ht" : "01:22:25", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "21449", "st" : "21449", "snt" : "0", "e" : "6342532", "ea" : "6342532", "ena" : "0", "c" : "5243490", "a" : "1099042", "tv" : "10486980", "vb" : "853822", "vn" : "1849607", "vp" : "0", "vv" : "7757861", "vl" : "0", "van" : "25690", "vnom" : "7757861", "cand" : [ 
{ "seq" : "5", "sqcand" : "60000605121", "n" : "177", "nm" : "PASTOR PEDRO RIBEIRO", "cc" : "PSL", "nv" : "DR WILSON MATOS", "ns1" : "DR WILSON MATOS", "nv" : "FÁTIMA RIBEIRO", "ns2" : "FÁTIMA RIBEIRO", "e" : "n", "v" : "334561", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "60000605120", "n" : "178", "nm" : "DR MÁRCIO PINHEIRO", "cc" : "PSL", "nv" : "ALBINO OLIVEIRA", "ns1" : "ALBINO OLIVEIRA", "nv" : "INSPETOR ALBERTO", "ns2" : "INSPETOR ALBERTO", "e" : "n", "v" : "183949", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "60000611596", "n" : "456", "nm" : "DRA. MAYRA", "cc" : "PSDB - PSDB \/ PROS", "nv" : "ROSENBERG FREITAS", "ns1" : "ROSENBERG FREITAS", "nv" : "JOSE NILSON", "ns2" : "JOSE NILSON", "e" : "n", "v" : "882019", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "60000616813", "n" : "290", "nm" : "ALEXANDRE BARROSO", "cc" : "PCO", "nv" : "RONALD MEDEIROS", "ns1" : "RONALD MEDEIROS", "nv" : "PATRICIA BRAGA", "ns2" : "PATRICIA BRAGA", "e" : "n", "v" : "0", "vap" : "11939", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "9", "sqcand" : "60000622554", "n" : "180", "nm" : "JOÃO SARAIVA", "cc" : "REDE", "nv" : "PAULO ROBERTO NEVES PEREIRA", "ns1" : "PAULO ROBERTO NEVES PEREIRA", "nv" : "PROFESSOR PEDRO JORGE", "ns2" : "PROFESSOR PEDRO JORGE", "e" : "n", "v" : "21654", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "60000620531", "n" : "505", "nm" : "ANNA KARINA", "cc" : "PSOL", "nv" : "NERICILDA ROCHA", "ns2" : "NERICILDA ROCHA", "nv" : "ANA VLÁDIA", "ns1" : "ANA VLÁDIA", "e" : "n", "v" : "316922", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "60000605116", "n" : "151", "nm" : "EUNÍCIO", "cc" : "MDB - MDB \/ PHS \/ AVANTE \/ SOLIDARIEDADE \/ PSD \/ PSC \/ PODE \/ PRB", "nv" : "EDMILSON BASTOS", "ns2" : "EDMILSON BASTOS", "nv" : "GAUDENCIO LUCENA", "ns1" : "GAUDENCIO LUCENA", "e" : "n", "v" : "1313793", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "60000611597", "n" : "900", "nm" : "EDUARDO GIRÃO", "cc" : "PROS - PSDB \/ PROS", "nv" : "DR. GUIMARÃES", "ns2" : "DR. GUIMARÃES", "nv" : "SARGENTO REGINAURO", "ns1" : "SARGENTO REGINAURO", "e" : "s", "v" : "1325786", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "60000620377", "n" : "360", "nm" : "ROBERT BURNS", "cc" : "PTC", "nv" : "NONATINHO", "ns1" : "NONATINHO", "nv" : "RAIMUNDA GOMES SILVA CAETANO B", "ns2" : "RAIMUNDA GOMES SILVA CAETANO B", "e" : "n", "v" : "0", "vap" : "13751", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "8", "sqcand" : "60000620534", "n" : "500", "nm" : "PASTOR SIMÕES", "cc" : "PSOL", "nv" : "ALEXANDRE UCHOA", "ns1" : "ALEXANDRE UCHOA", "nv" : "CHIQUINHO DO TURURU", "ns2" : "CHIQUINHO DO TURURU", "e" : "n", "v" : "150644", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "60000610981", "n" : "123", "nm" : "CID GOMES", "cc" : "PDT - PT \/ PDT \/ PP \/ PSB \/ PR \/ PTB \/ DEM \/ PC do B \/ PPS \/ PRP \/ PV \/ PMN \/ PPL \/ PATRI \/ PRTB \/ PMB", "nv" : "JULIO VENTURA", "ns2" : "JULIO VENTURA", "nv" : "PRISCO BEZERRA", "ns1" : "PRISCO BEZERRA", "e" : "s", "v" : "3228533", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }