
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "es", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "20:49:21", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "8725", "st" : "8725", "snt" : "0", "e" : "2753585", "ea" : "2753585", "ena" : "0", "c" : "2223207", "a" : "530378", "tv" : "4446414", "vb" : "346395", "vn" : "513931", "vp" : "0", "vv" : "3586088", "vl" : "0", "van" : "0", "vnom" : "3586088", "cand" : [ 
{ "seq" : "5", "sqcand" : "80000607527", "n" : "177", "nm" : "SUBTENENTE ASSIS", "cc" : "PSL - PR \/ PRB \/ PSL", "nv" : "FLAVIO MELLO SANT ANA", "ns2" : "FLAVIO MELLO SANT ANA", "nv" : "SARGENTO ROBSON", "ns1" : "SARGENTO ROBSON", "e" : "n", "v" : "247165", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "80000612948", "n" : "181", "nm" : "FABIANO CONTARATO", "cc" : "REDE - PRTB \/ REDE \/ PODE \/ MDB \/ PMN \/ PATRI", "nv" : "BENTO", "ns2" : "BENTO", "nv" : "ANA PAULA TONGO", "ns1" : "ANA PAULA TONGO", "e" : "s", "v" : "1117036", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "80000626749", "n" : "131", "nm" : "CÉLIA TAVARES", "cc" : "PT", "nv" : "COTINHA", "ns2" : "COTINHA", "nv" : "PERLY CIPRIANO", "ns1" : "PERLY CIPRIANO", "e" : "n", "v" : "164845", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "80000625744", "n" : "211", "nm" : "MAURO RIBEIRO", "cc" : "PCB - PSOL \/ PCB", "nv" : "DINHO", "ns2" : "DINHO", "nv" : "MANOEL TAVARES", "ns1" : "MANOEL TAVARES", "e" : "n", "v" : "8287", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "80000627612", "n" : "144", "nm" : "HELDER CARNIELLI", "cc" : "PTB - PTB \/ PMB", "nv" : "ROBERTO MARTINS", "ns1" : "ROBERTO MARTINS", "nv" : "NILO FRANCO", "ns2" : "NILO FRANCO", "e" : "n", "v" : "22844", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "80000600185", "n" : "300", "nm" : "ULISSES PINCELLI", "cc" : "NOVO", "nv" : "FRED ESTEVES", "ns2" : "FRED ESTEVES", "nv" : "GIULIANO SANDRI", "ns1" : "GIULIANO SANDRI", "e" : "n", "v" : "37119", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "80000627979", "n" : "355", "nm" : "ROGERIO BERNARDO", "cc" : "PMB - PTB \/ PMB", "nv" : "VAGNER TONETTO", "ns2" : "VAGNER TONETTO", "nv" : "CINTIA TEIXEIRA", "ns1" : "CINTIA TEIXEIRA", "e" : "n", "v" : "9531", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "80000625509", "n" : "456", "nm" : "RICARDO FERRAÇO", "cc" : "PSDB - PSB \/ PHS \/ PROS \/ PV \/ PSC \/ AVANTE \/ PTC \/ PPS \/ PSDB \/ DEM \/ PDT \/ PP \/ PC do B \/ PPL \/ DC \/ SOLIDARIEDADE \/ PRP \/ PSD", "nv" : "JURANDY LOUREIRO", "ns2" : "JURANDY LOUREIRO", "nv" : "EUTEMAR VENTURIM", "ns1" : "EUTEMAR VENTURIM", "e" : "n", "v" : "480122", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "80000625723", "n" : "500", "nm" : "LIU KATRINE", "cc" : "PSOL - PSOL \/ PCB", "nv" : "TONI CABANO", "ns1" : "TONI CABANO", "nv" : "WILSON JUNIOR", "ns2" : "WILSON JUNIOR", "e" : "n", "v" : "24496", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "80000607499", "n" : "222", "nm" : "MAGNO MALTA", "cc" : "PR - PR \/ PRB \/ PSL", "nv" : "CARLOS SALVADOR", "ns1" : "CARLOS SALVADOR", "nv" : "MOABE SOUZA", "ns2" : "MOABE SOUZA", "e" : "n", "v" : "611284", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "80000625508", "n" : "234", "nm" : "MARCOS DO VAL", "cc" : "PPS - PSB \/ PHS \/ PROS \/ PV \/ PSC \/ AVANTE \/ PTC \/ PPS \/ PSDB \/ DEM \/ PDT \/ PP \/ PC do B \/ PPL \/ DC \/ SOLIDARIEDADE \/ PRP \/ PSD", "nv" : "ROSANA FOERST", "ns1" : "ROSANA FOERST", "nv" : "RONALDO LIBARDI", "ns2" : "RONALDO LIBARDI", "e" : "s", "v" : "863359", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }