
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "go", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "22:31:17", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "13995", "st" : "13995", "snt" : "0", "e" : "4453034", "ea" : "4453034", "ena" : "0", "c" : "3553706", "a" : "899328", "tv" : "7107412", "vb" : "560309", "vn" : "1029774", "vp" : "0", "vv" : "5517329", "vl" : "0", "van" : "0", "vnom" : "5517329", "cand" : [ 
{ "seq" : "8", "sqcand" : "90000619105", "n" : "135", "nm" : "LUIS CÉSAR BUENO", "cc" : "PT - PT \/ PC do B", "nv" : "SORMANI IRINEU", "ns2" : "SORMANI IRINEU", "nv" : "PROFESSORA NEUSA", "ns1" : "PROFESSORA NEUSA", "e" : "n", "v" : "101743", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "90000609449", "n" : "405", "nm" : "LÚCIA VÂNIA", "cc" : "PSB - PSDB \/ PTB \/ PSB \/ PR \/ PSD \/ PPS \/ SOLIDARIEDADE \/ PV \/ AVANTE \/ PATRI** \/ REDE", "nv" : "FERNANDO SAFATLE", "ns2" : "FERNANDO SAFATLE", "nv" : "JOSÉ VITTI", "ns1" : "JOSÉ VITTI", "e" : "n", "v" : "519691", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "90000621005", "n" : "210", "nm" : "PROFESSORA MAGDA BORGES", "cc" : "PCB", "nv" : "DONA TERESINHA", "ns2" : "DONA TERESINHA", "nv" : "IVAN FARIA", "ns1" : "IVAN FARIA", "e" : "n", "v" : "20623", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "90000619107", "n" : "131", "nm" : "PROFESSORA GELI", "cc" : "PT - PT \/ PC do B", "nv" : "PROFESSOR ANTONIO BITES", "ns1" : "PROFESSOR ANTONIO BITES", "nv" : "MARDÔNIO", "ns2" : "MARDÔNIO", "e" : "n", "v" : "132773", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "90000621192", "n" : "510", "nm" : "SANTANA PIRES", "cc" : "PATRI", "nv" : "PEDRAO", "ns1" : "PEDRAO", "nv" : "GUARDA CHUVA", "ns2" : "GUARDA CHUVA", "e" : "n", "v" : "0", "vap" : "6062", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "3", "sqcand" : "90000613469", "n" : "251", "nm" : "WILDER MORAIS", "cc" : "DEM - DEM \/ PRP \/ PROS \/ PMN \/ PMB \/ PSC \/ DC \/ PSL \/ PODE \/ PTC \/ PRTB \/ PDT", "nv" : "DOMINGOS SÁVIO", "ns1" : "DOMINGOS SÁVIO", "nv" : "BISPO ABIGAIL ALMEIDA", "ns2" : "BISPO ABIGAIL ALMEIDA", "e" : "n", "v" : "796387", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "12", "sqcand" : "90000618808", "n" : "290", "nm" : "PROFESSOR ALESSANDRO AQUINO", "cc" : "PCO", "nv" : "TIÃO DA CONSTRUÇÃO CIVIL", "ns1" : "TIÃO DA CONSTRUÇÃO CIVIL", "nv" : "SSIS DO INDICATO", "ns2" : "SSIS DO INDICATO", "e" : "n", "v" : "0", "vap" : "8763", "dsit" : "Deferido", "svnom" : "s" }, 
{ "seq" : "6", "sqcand" : "90000609233", "n" : "150", "nm" : "AGENOR", "cc" : "MDB - MDB \/ PRB \/ PHS \/ PP", "nv" : "QUIRINO", "ns1" : "QUIRINO", "nv" : "VERA LÚCIA", "ns2" : "VERA LÚCIA", "e" : "n", "v" : "196614", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "90000613472", "n" : "444", "nm" : "JORGE KAJURU", "cc" : "PRP - DEM \/ PRP \/ PROS \/ PMN \/ PMB \/ PSC \/ DC \/ PSL \/ PODE \/ PTC \/ PRTB \/ PDT", "nv" : "MILTON MERCÊZ", "ns2" : "MILTON MERCÊZ", "nv" : "BENJAMIN BEZE JUNIOR", "ns1" : "BENJAMIN BEZE JUNIOR", "e" : "s", "v" : "1557415", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "90000602021", "n" : "500", "nm" : "FABRÍCIO ROSA", "cc" : "PSOL", "nv" : "FABRICIO COSTA", "ns2" : "FABRICIO COSTA", "nv" : "PROFESSOR AUGUSTINHO", "ns1" : "PROFESSOR AUGUSTINHO", "e" : "n", "v" : "45833", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "90000609445", "n" : "456", "nm" : "MARCONI PERILLO", "cc" : "PSDB - PSDB \/ PTB \/ PSB \/ PR \/ PSD \/ PPS \/ SOLIDARIEDADE \/ PV \/ AVANTE \/ PATRI** \/ REDE", "nv" : "ALEANDRA SOUSA", "ns2" : "ALEANDRA SOUSA", "nv" : "VILMAR ROCHA", "ns1" : "VILMAR ROCHA", "e" : "n", "v" : "416613", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "90000609234", "n" : "111", "nm" : "VANDERLAN", "cc" : "PP - MDB \/ PRB \/ PHS \/ PP", "nv" : "JADER MELO", "ns2" : "JADER MELO", "nv" : "PEDRO CHAVES", "ns1" : "PEDRO CHAVES", "e" : "s", "v" : "1729637", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }