
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "ro", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "20:50:12", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "4181", "st" : "4181", "snt" : "0", "e" : "1175133", "ea" : "1175133", "ena" : "0", "c" : "912914", "a" : "262219", "tv" : "1825828", "vb" : "125915", "vn" : "228105", "vp" : "0", "vv" : "1350564", "vl" : "0", "van" : "121244", "vnom" : "1350564", "cand" : [ 
{ "seq" : "4", "sqcand" : "220000604629", "n" : "400", "nm" : "JESUALDO PIRES", "cc" : "PSB - PDT \/ PSB \/ PTB \/ DC \/ PP \/ PR \/ SOLIDARIEDADE \/ PTC \/ PT**", "nv" : "DELEGADO JULIO CÉSAR", "ns1" : "DELEGADO JULIO CÉSAR", "nv" : "JAIR MARINHO", "ns2" : "JAIR MARINHO", "e" : "n", "v" : "195641", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "220000627641", "n" : "180", "nm" : "ALUÍZIO VIDAL", "cc" : "REDE - REDE \/ PPS \/ PRP", "nv" : "IVANEIDE BANDEIRA", "ns2" : "IVANEIDE BANDEIRA", "nv" : "DELEGADO MÁRCIO MAIA", "ns1" : "DELEGADO MÁRCIO MAIA", "e" : "n", "v" : "51917", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "220000627024", "n" : "280", "nm" : "TED WILSON", "cc" : "PRTB", "nv" : "KARLA SANTOS", "ns1" : "KARLA SANTOS", "nv" : "EDUARDO MENDES", "ns2" : "EDUARDO MENDES", "e" : "n", "v" : "13091", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "13", "sqcand" : "220000621885", "n" : "167", "nm" : "PAULO CADILLAC", "cc" : "PSTU", "nv" : "MARCIO MARTINS", "ns1" : "MARCIO MARTINS", "nv" : "KAREN FERNNADES", "ns2" : "KAREN FERNNADES", "e" : "n", "v" : "0", "vap" : "1612", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "8", "sqcand" : "220000609854", "n" : "100", "nm" : "PASTOR EDÉSIO FERNANDES", "cc" : "PRB - PSDB \/ DEM \/ PSD \/ PRB \/ PATRI", "nv" : "SALENO CANDIDO", "ns2" : "SALENO CANDIDO", "nv" : "ODACIR SOARES", "ns1" : "ODACIR SOARES", "e" : "n", "v" : "43539", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "220000627644", "n" : "234", "nm" : "BOSCO DA FEDERAL", "cc" : "PPS - REDE \/ PPS \/ PRP", "nv" : "MARQUINHOS NEVES", "ns1" : "MARQUINHOS NEVES", "nv" : "EDSON SILVA", "ns2" : "EDSON SILVA", "e" : "n", "v" : "0", "vap" : "15584", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "12", "sqcand" : "220000622268", "n" : "133", "nm" : "FÁTIMA CLEIDE", "cc" : "PT - PT \/ PSOL", "nv" : "LHANO FERNANDES", "ns1" : "LHANO FERNANDES", "nv" : "JOSUÉ DE SOUZA", "ns2" : "JOSUÉ DE SOUZA", "e" : "n", "v" : "0", "vap" : "104048", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "5", "sqcand" : "220000604628", "n" : "111", "nm" : "CARLOS MAGNO", "cc" : "PP - PDT \/ PSB \/ PTB \/ DC \/ PP \/ PR \/ SOLIDARIEDADE \/ PTC \/ PT**", "nv" : "AMIR LANDO ", "ns1" : "AMIR LANDO ", "nv" : "EDSON  DEPIERI", "ns2" : "EDSON  DEPIERI", "e" : "n", "v" : "163859", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "220000618467", "n" : "152", "nm" : "CONFUCIO MOURA", "cc" : "MDB - MDB \/ PODE \/ PMN \/ PSC \/ PC do B \/ PHS \/ PROS \/ PV", "nv" : "MARIA ELIZA", "ns1" : "MARIA ELIZA", "nv" : "CARLOS MILTON MORAIS", "ns2" : "CARLOS MILTON MORAIS", "e" : "s", "v" : "230361", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "220000609853", "n" : "255", "nm" : "MARCOS ROGÉRIO", "cc" : "DEM - PSDB \/ DEM \/ PSD \/ PRB \/ PATRI", "nv" : "PASTOR SEVERINO", "ns2" : "PASTOR SEVERINO", "nv" : "SAMUEL ARAUJO", "ns1" : "SAMUEL ARAUJO", "e" : "s", "v" : "324939", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "220000625840", "n" : "177", "nm" : "JAIME BAGATTOLI", "cc" : "PSL", "nv" : "JOÃO CIPRIANO", "ns1" : "JOÃO CIPRIANO", "nv" : "LUIZ DA LAMMY", "ns2" : "LUIZ DA LAMMY", "e" : "n", "v" : "212077", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "220000618466", "n" : "151", "nm" : "VALDIR RAUPP", "cc" : "MDB - MDB \/ PODE \/ PMN \/ PSC \/ PC do B \/ PHS \/ PROS \/ PV", "nv" : "CLÁUDIA  MUNIZ", "ns2" : "CLÁUDIA  MUNIZ", "nv" : "TOMAS CORREIA ", "ns1" : "TOMAS CORREIA ", "e" : "n", "v" : "80370", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "220000600266", "n" : "300", "nm" : "FABRICIO JURADO", "cc" : "NOVO", "nv" : "ALAN ARAIS", "ns2" : "ALAN ARAIS", "nv" : "FERNANDO BUENO", "ns1" : "FERNANDO BUENO", "e" : "n", "v" : "34770", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }