
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "to", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "20:57:33", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "3832", "st" : "3832", "snt" : "0", "e" : "1038754", "ea" : "1038754", "ena" : "0", "c" : "831214", "a" : "207540", "tv" : "1662428", "vb" : "76167", "vn" : "311558", "vp" : "0", "vv" : "1274703", "vl" : "0", "van" : "0", "vnom" : "1274703", "cand" : [ 
{ "seq" : "4", "sqcand" : "270000602794", "n" : "222", "nm" : "VICENTINHO", "cc" : "PR - PSB \/ MDB \/ PR \/ PODE \/ PSC \/ PSDB", "nv" : "ANTONIO EDINALDO DA LUZ LUCENA", "ns1" : "ANTONIO EDINALDO DA LUZ LUCENA", "nv" : "HOMERO BARRETO", "ns2" : "HOMERO BARRETO", "e" : "n", "v" : "176012", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "270000625482", "n" : "177", "nm" : "ANTÔNIO JORGE", "cc" : "PSL", "nv" : "RENATO BASSANI", "ns2" : "RENATO BASSANI", "nv" : "CORONEL PARENTE", "ns1" : "CORONEL PARENTE", "e" : "n", "v" : "66089", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "270000627774", "n" : "500", "nm" : "MELK AIRES", "cc" : "PSOL", "nv" : "EDGAR GOMES", "ns1" : "EDGAR GOMES", "nv" : "CRISTOVAO", "ns2" : "CRISTOVAO", "e" : "n", "v" : "12312", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "270000626087", "n" : "555", "nm" : "IRAJÁ", "cc" : "PSD - REDE \/ PRTB \/ PTB \/ PC do B \/ PT \/ PV \/ PDT \/ PSD", "nv" : "MARCOS", "ns1" : "MARCOS", "nv" : "TERCILIANO GOMES", "ns2" : "TERCILIANO GOMES", "e" : "s", "v" : "214355", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "270000602793", "n" : "455", "nm" : "ATAÍDES OLIVEIRA", "cc" : "PSDB - PSB \/ MDB \/ PR \/ PODE \/ PSC \/ PSDB", "nv" : "FREIRE JUNIOR", "ns1" : "FREIRE JUNIOR", "nv" : "FERRERINHA", "ns2" : "FERRERINHA", "e" : "n", "v" : "170012", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "270000625486", "n" : "170", "nm" : "FARLEI O FEDERAL", "cc" : "PSL", "nv" : "TÚLIO JORGE CHEGURY", "ns2" : "TÚLIO JORGE CHEGURY", "nv" : "FELIPE P. JAIME", "ns1" : "FELIPE P. JAIME", "e" : "n", "v" : "65676", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "270000629454", "n" : "777", "nm" : "EDUARDO GOMES", "cc" : "SOLIDARIEDADE - PHS \/ SOLIDARIEDADE \/ PP \/ DEM \/ PTC \/ PRB \/ AVANTE \/ PATRI \/ PROS", "nv" : "OGARI PACHECO", "ns2" : "OGARI PACHECO", "nv" : "SIQUEIRA CAMPOS", "ns1" : "SIQUEIRA CAMPOS", "e" : "s", "v" : "248358", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "270000626090", "n" : "131", "nm" : "PAULO MOURÃO", "cc" : "PT - REDE \/ PRTB \/ PTB \/ PC do B \/ PT \/ PV \/ PDT \/ PSD", "nv" : "PROFESSORA GERMANA", "ns1" : "PROFESSORA GERMANA", "nv" : "DR. LUIS ANTONIO", "ns2" : "DR. LUIS ANTONIO", "e" : "n", "v" : "137654", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "270000618820", "n" : "101", "nm" : "CÉSAR HALUM", "cc" : "PRB - PHS \/ SOLIDARIEDADE \/ PP \/ DEM \/ PTC \/ PRB \/ AVANTE \/ PATRI \/ PROS", "nv" : "AQUILES PEREIRA", "ns2" : "AQUILES PEREIRA", "nv" : "DARCI GARCIA", "ns1" : "DARCI GARCIA", "e" : "n", "v" : "184235", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" } ] }