
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "se", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "23:18:03", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "5137", "st" : "5137", "snt" : "0", "e" : "1576352", "ea" : "1576352", "ena" : "0", "c" : "1279582", "a" : "296770", "tv" : "2559164", "vb" : "191720", "vn" : "539360", "vp" : "0", "vv" : "1828084", "vl" : "0", "van" : "0", "vnom" : "1828084", "cand" : [ 
{ "seq" : "9", "sqcand" : "260000624581", "n" : "177", "nm" : "CADU SILVA", "cc" : "PSL", "nv" : "JOSÉ ALBERTO", "ns1" : "JOSÉ ALBERTO", "nv" : "LUIZ CARLOS BARRETO", "ns2" : "LUIZ CARLOS BARRETO", "e" : "n", "v" : "43215", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "260000621984", "n" : "100", "nm" : "PASTOR HELENO", "cc" : "PRB - PRB \/ PPS \/ PSC \/ PR \/ PTC \/ PSDB \/ SOLIDARIEDADE", "nv" : "ADAILTON SOUSA", "ns1" : "ADAILTON SOUSA", "nv" : "PASTORA SALETE", "ns2" : "PASTORA SALETE", "e" : "n", "v" : "165039", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "260000623589", "n" : "155", "nm" : "JACKSON BARRETO", "cc" : "MDB - PP \/ MDB \/ DC \/ PC do B \/ PSD \/ PT \/ PHS", "nv" : "SERGIO GAMA", "ns1" : "SERGIO GAMA", "nv" : "ALEXANDRE FILADELFO", "ns2" : "ALEXANDRE FILADELFO", "e" : "n", "v" : "204677", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "260000614793", "n" : "540", "nm" : "HENRI CLAY", "cc" : "PPL - PSB \/ PDT \/ PPL \/ PTB \/ PROS \/ PRP", "nv" : "JOSE ORLANDO MELO", "ns2" : "JOSE ORLANDO MELO", "nv" : "MARCOS CRUZ", "ns1" : "MARCOS CRUZ", "e" : "n", "v" : "109562", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "260000621976", "n" : "200", "nm" : "ANDRÉ MOURA", "cc" : "PSC - PRB \/ PPS \/ PSC \/ PR \/ PTC \/ PSDB \/ SOLIDARIEDADE", "nv" : "LUZIA DE AGUINALDO DE VERSO", "ns1" : "LUZIA DE AGUINALDO DE VERSO", "nv" : "FERNANDO NORONHA", "ns2" : "FERNANDO NORONHA", "e" : "n", "v" : "251213", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "260000623617", "n" : "131", "nm" : "ROGERIO CARVALHO SANTOS", "cc" : "PT - PP \/ MDB \/ DC \/ PC do B \/ PSD \/ PT \/ PHS", "nv" : "MARIA DA TAIÇOCA", "ns2" : "MARIA DA TAIÇOCA", "nv" : "JORGE MITIDIERI", "ns1" : "JORGE MITIDIERI", "e" : "s", "v" : "300247", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "260000610534", "n" : "433", "nm" : "REYNALDO NUNES", "cc" : "PV - DEM \/ PRTB \/ PV", "nv" : "WAGNER BARRETO SOARES", "ns1" : "WAGNER BARRETO SOARES", "nv" : "SAULO MENDONÇA", "ns2" : "SAULO MENDONÇA", "e" : "n", "v" : "27147", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "260000600292", "n" : "505", "nm" : "PROFESSOR JOSSIMÁRIO MICK", "cc" : "PSOL", "nv" : "BISPO ANTÔNIO", "ns2" : "BISPO ANTÔNIO", "nv" : "ANA CRISTINA", "ns1" : "ANA CRISTINA", "e" : "n", "v" : "11650", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "260000600284", "n" : "500", "nm" : "PROFESSORA SONIA MEIRE", "cc" : "PSOL", "nv" : "ADELMO TORRES", "ns1" : "ADELMO TORRES", "nv" : "BADO ARTES", "ns2" : "BADO ARTES", "e" : "n", "v" : "62770", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "260000601810", "n" : "181", "nm" : "DELEGADO ALESSANDRO VIEIRA", "cc" : "REDE", "nv" : "MAJOR ILDOMARIO", "ns2" : "MAJOR ILDOMARIO", "nv" : "FERNANDO CARVALHO", "ns1" : "FERNANDO CARVALHO", "e" : "s", "v" : "474449", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "260000614792", "n" : "404", "nm" : "VALADARES", "cc" : "PSB - PSB \/ PDT \/ PPL \/ PTB \/ PROS \/ PRP", "nv" : "CRIS TEIXEIRA", "ns1" : "CRIS TEIXEIRA", "nv" : "ELBER BATALHA", "ns2" : "ELBER BATALHA", "e" : "n", "v" : "175155", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "12", "sqcand" : "260000610791", "n" : "161", "nm" : "CLARCKSON MESSIAS", "cc" : "PSTU", "nv" : "CARLOS DOS SANTOS", "ns1" : "CARLOS DOS SANTOS", "nv" : "VITOR HUGO", "ns2" : "VITOR HUGO", "e" : "n", "v" : "2960", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }