
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "mt", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "22:28:24", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "7247", "st" : "7247", "snt" : "0", "e" : "2329374", "ea" : "2329374", "ena" : "0", "c" : "1757368", "a" : "572006", "tv" : "3514736", "vb" : "274527", "vn" : "478374", "vp" : "0", "vv" : "2752935", "vl" : "0", "van" : "8900", "vnom" : "2752935", "cand" : [ 
{ "seq" : "2", "sqcand" : "110000612714", "n" : "251", "nm" : "JAYME CAMPOS", "cc" : "DEM - DEM \/ PSD \/ PDT \/ PSC \/ MDB \/ PMB \/ PHS \/ PTC", "nv" : "FABIO GARCIA", "ns1" : "FABIO GARCIA", "nv" : "CÂNDIDA FARIAS", "ns2" : "CÂNDIDA FARIAS", "e" : "s", "v" : "490699", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "110000609944", "n" : "654", "nm" : "PROFESSORA MARIA LUCIA", "cc" : "PC do B - PR \/ PV \/ PRB \/ PT \/ PTB \/ PODE \/ PMN \/ PC do B \/ PROS \/ PP", "nv" : "PROFESSOR GILMAR SOARES", "ns1" : "PROFESSOR GILMAR SOARES", "nv" : "ALUISIO ARRUDA", "ns2" : "ALUISIO ARRUDA", "e" : "n", "v" : "172259", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "110000622010", "n" : "188", "nm" : "SEBASTIÃO CARLOS", "cc" : "REDE - REDE \/ PPL", "nv" : "PROFESSOR MAURO", "ns2" : "PROFESSOR MAURO", "nv" : "GEORGE RIBEIRO", "ns1" : "GEORGE RIBEIRO", "e" : "n", "v" : "0", "vap" : "8900", "dsit" : "Deferido", "svnom" : "s" }, 
{ "seq" : "1", "sqcand" : "110000613185", "n" : "170", "nm" : "JUIZA SELMA ARRUDA", "cc" : "PSL - PSL \/ PPS \/ PSB \/ DC \/ PRP \/ PSDB \/ PATRI \/ AVANTE \/ SOLIDARIEDADE", "nv" : "CLERIE FABIANA", "ns2" : "CLERIE FABIANA", "nv" : "BETO POSSAMAI", "ns1" : "BETO POSSAMAI", "e" : "s", "v" : "678542", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "110000621994", "n" : "547", "nm" : "ALADIR", "cc" : "PPL - REDE \/ PPL", "nv" : "SONIA MARIA", "ns1" : "SONIA MARIA", "nv" : "GORDO PÉ NO CHÃO", "ns2" : "GORDO PÉ NO CHÃO", "e" : "n", "v" : "9325", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "110000600720", "n" : "300", "nm" : "DR WALDIR CALDAS", "cc" : "NOVO", "nv" : "GIVANILDO GOMES", "ns1" : "GIVANILDO GOMES", "nv" : "NICACIO LEMES JR", "ns2" : "NICACIO LEMES JR", "e" : "n", "v" : "71494", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "110000613182", "n" : "456", "nm" : "NILSON LEITÃO", "cc" : "PSDB - PSL \/ PPS \/ PSB \/ DC \/ PRP \/ PSDB \/ PATRI \/ AVANTE \/ SOLIDARIEDADE", "nv" : "REJANE GARCIA", "ns2" : "REJANE GARCIA", "nv" : "LUIS CARLOS NIGRO", "ns1" : "LUIS CARLOS NIGRO", "e" : "n", "v" : "330430", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "110000607694", "n" : "500", "nm" : "PROCURADOR MAURO", "cc" : "PSOL", "nv" : "DR. JOSÉ ROBERTO", "ns1" : "DR. JOSÉ ROBERTO", "nv" : "MANOEL PARRIÃO BIRINHA", "ns2" : "MANOEL PARRIÃO BIRINHA", "e" : "n", "v" : "226053", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "110000609946", "n" : "100", "nm" : "ADILTON SACHETTI", "cc" : "PRB - PR \/ PV \/ PRB \/ PT \/ PTB \/ PODE \/ PMN \/ PC do B \/ PROS \/ PP", "nv" : "CHICO GALINDO", "ns1" : "CHICO GALINDO", "nv" : "ALESSANDRA NICOLLI", "ns2" : "ALESSANDRA NICOLLI", "e" : "n", "v" : "333082", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "110000612717", "n" : "555", "nm" : "FÁVARO", "cc" : "PSD - DEM \/ PSD \/ PDT \/ PSC \/ MDB \/ PMB \/ PHS \/ PTC", "nv" : "JOSE LACERDA", "ns2" : "JOSE LACERDA", "nv" : "GERALDO MACEDO", "ns1" : "GERALDO MACEDO", "e" : "n", "v" : "434972", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "110000607696", "n" : "505", "nm" : "GILBERTO LOPES FILHO", "cc" : "PSOL", "nv" : "EVANDRO VANDOKA", "ns1" : "EVANDRO VANDOKA", "nv" : "JB", "ns2" : "JB", "e" : "n", "v" : "6079", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }