
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "ap", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "21:46:37", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "1632", "st" : "1632", "snt" : "0", "e" : "511824", "ea" : "511824", "ena" : "0", "c" : "426382", "a" : "85442", "tv" : "852764", "vb" : "32187", "vn" : "113978", "vp" : "0", "vv" : "697555", "vl" : "0", "van" : "9044", "vnom" : "697555", "cand" : [ 
{ "seq" : "6", "sqcand" : "30000605846", "n" : "151", "nm" : "FÁTIMA PELAES", "cc" : "MDB", "nv" : "WANDERLEY AZEVEDO", "ns1" : "WANDERLEY AZEVEDO", "nv" : "LÚCIA COÊLHO", "ns2" : "LÚCIA COÊLHO", "e" : "n", "v" : "40403", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "30000618165", "n" : "212", "nm" : "JOAQUINA LINO", "cc" : "PCB", "nv" : "MARILEIDE LOPES", "ns1" : "MARILEIDE LOPES", "nv" : "MANOEL REINALDO", "ns2" : "MANOEL REINALDO", "e" : "n", "v" : "0", "vap" : "9044", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "1", "sqcand" : "30000620104", "n" : "180", "nm" : "RANDOLFE ", "cc" : "REDE - DEM \/ REDE \/ PSDB \/ PPL \/ PP \/ PSC \/ AVANTE \/ PSD \/ PODE \/ SOLIDARIEDADE", "nv" : "PASTOR GAIA", "ns2" : "PASTOR GAIA", "nv" : "ALBERTO DAVID", "ns1" : "ALBERTO DAVID", "e" : "s", "v" : "264798", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "12", "sqcand" : "30000602694", "n" : "231", "nm" : "JORGE AMANAJAS", "cc" : "PPS - PPS** \/ PHS \/ PR \/ PSL", "nv" : "SONIZE BARBOSA", "ns1" : "SONIZE BARBOSA", "nv" : "JOSMAR PINTO", "ns2" : "JOSMAR PINTO", "e" : "n", "v" : "0", "vap" : "52768", "dsit" : "Indeferido", "svnom" : "s" }, 
{ "seq" : "10", "sqcand" : "30000622839", "n" : "333", "nm" : "WAGNER GOMES", "cc" : "PMN - PV \/ PMN \/ PSOL", "nv" : "RUBEN BEMERGUY", "ns1" : "RUBEN BEMERGUY", "nv" : "PAIZÃO", "ns2" : "PAIZÃO", "e" : "n", "v" : "5605", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "30000623196", "n" : "360", "nm" : "GUARACY", "cc" : "PTC", "nv" : "JOSELYO AGUIAR", "ns1" : "JOSELYO AGUIAR", "nv" : "JOELMA CHAGAS", "ns2" : "JOELMA CHAGAS", "e" : "n", "v" : "40558", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "30000610398", "n" : "161", "nm" : "DR. DAVI", "cc" : "PSTU", "nv" : "SERGIO", "ns2" : "SERGIO", "nv" : "ELISANGELA MARQUES", "ns1" : "ELISANGELA MARQUES", "e" : "n", "v" : "5641", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "30000620046", "n" : "400", "nm" : "JANETE CAPIBERIBE", "cc" : "PSB - PT \/ PSB", "nv" : "NUNES", "ns1" : "NUNES", "nv" : "SANDRA ALMEIDA", "ns2" : "SANDRA ALMEIDA", "e" : "n", "v" : "125123", "vap" : "0", "dsit" : "Indeferido com recurso", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "30000602700", "n" : "177", "nm" : "DR RICARDO SANTOS", "cc" : "PSL - PPS** \/ PHS \/ PR \/ PSL", "nv" : "ROSE MIRANDA", "ns1" : "ROSE MIRANDA", "nv" : "NELSON ALMEIDA", "ns2" : "NELSON ALMEIDA", "e" : "n", "v" : "11882", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "30000607892", "n" : "147", "nm" : "LUCAS BARRETO", "cc" : "PTB", "nv" : "PAULO ALBUQUERQUE", "ns1" : "PAULO ALBUQUERQUE", "nv" : "PATRICIA COSTA", "ns2" : "PATRICIA COSTA", "e" : "s", "v" : "128186", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "30000620108", "n" : "450", "nm" : "BALA ROCHA", "cc" : "PSDB - DEM \/ REDE \/ PSDB \/ PPL \/ PP \/ PSC \/ AVANTE \/ PSD \/ PODE \/ SOLIDARIEDADE", "nv" : "EDIVAL TORK", "ns2" : "EDIVAL TORK", "nv" : "DORIMAR BARBOSA", "ns1" : "DORIMAR BARBOSA", "e" : "n", "v" : "45999", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "30000605843", "n" : "152", "nm" : "GILVAM BORGES", "cc" : "MDB", "nv" : "GEOVANI BORGES ", "ns1" : "GEOVANI BORGES ", "nv" : "MIGUEL GIL", "ns2" : "MIGUEL GIL", "e" : "n", "v" : "29360", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }