
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "rj", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "23:30:58", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "33901", "st" : "33901", "snt" : "0", "e" : "12401199", "ea" : "12401199", "ena" : "0", "c" : "9474441", "a" : "2926758", "tv" : "18948882", "vb" : "1689111", "vn" : "3261171", "vp" : "0", "vv" : "13965981", "vl" : "0", "van" : "32619", "vnom" : "13965981", "cand" : [ 
{ "seq" : "15", "sqcand" : "190000607897", "n" : "160", "nm" : "SAMANTHA GUEDES", "cc" : "PSTU", "nv" : "MARIA ELISA GUIMARAES ", "ns2" : "MARIA ELISA GUIMARAES ", "nv" : "JUZERLEY ASSUNÇÃO", "ns1" : "JUZERLEY ASSUNÇÃO", "e" : "n", "v" : "13680", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "16", "sqcand" : "190000628395", "n" : "511", "nm" : "WALTER CRISTIE SILVA AGUIAR", "cc" : "PATRI - PRP \/ PRB \/ PTC \/ PATRI \/ PMB**", "nv" : "MAURO CUNHA", "ns2" : "MAURO CUNHA", "nv" : "CARLA JORDES", "ns1" : "CARLA JORDES", "e" : "n", "v" : "0", "vap" : "23803", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "14", "sqcand" : "190000628313", "n" : "355", "nm" : "GABRIELLE BURCCI", "cc" : "PMB", "nv" : "SIDCLEI BERNARDO", "ns1" : "SIDCLEI BERNARDO", "nv" : "SILVIO MALLET", "ns2" : "SILVIO MALLET", "e" : "n", "v" : "27081", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "190000610856", "n" : "188", "nm" : "MIRO TEIXEIRA", "cc" : "REDE - PODE \/ PR \/ REDE \/ PPL", "nv" : "VALERIA TATSCH", "ns2" : "VALERIA TATSCH", "nv" : "SONIA RABELLO", "ns1" : "SONIA RABELLO", "e" : "n", "v" : "430893", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "190000621820", "n" : "100", "nm" : "SENADOR EDUARDO LOPES", "cc" : "PRB - PRP \/ PRB \/ PTC \/ PATRI \/ PMB**", "nv" : "JANE CRIVELLA", "ns1" : "JANE CRIVELLA", "nv" : "GUEDES", "ns2" : "GUEDES", "e" : "n", "v" : "507850", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "13", "sqcand" : "190000607900", "n" : "161", "nm" : "CYRO CARGIA", "cc" : "PSTU", "nv" : "JULIA EBERHARDT", "ns1" : "JULIA EBERHARDT", "nv" : "SERGIO PEDIGÃO", "ns2" : "SERGIO PEDIGÃO", "e" : "n", "v" : "45588", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "190000612302", "n" : "200", "nm" : "PASTOR EVERALDO", "cc" : "PSC - PSC \/ PROS", "nv" : "DONIZETI PEREIRA", "ns1" : "DONIZETI PEREIRA", "nv" : "LAERCIO DE ALMEIDA", "ns2" : "LAERCIO DE ALMEIDA", "e" : "n", "v" : "360688", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "190000615552", "n" : "123", "nm" : "JOSE BONIFACIO", "cc" : "PDT - PDT \/ PSB", "nv" : "ALICE ALVES DOS SANTOS FIGUEIR", "ns2" : "ALICE ALVES DOS SANTOS FIGUEIR", "nv" : "MARIA JOSE LATGE KWAMME", "ns1" : "MARIA JOSE LATGE KWAMME", "e" : "n", "v" : "313265", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "190000602067", "n" : "500", "nm" : "CHICO ALENCAR", "cc" : "PSOL - PSOL \/ PCB", "nv" : "VANDERELEA AGUIAR", "ns1" : "VANDERELEA AGUIAR", "nv" : "DODORA MOTA", "ns2" : "DODORA MOTA", "e" : "n", "v" : "1281373", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "190000609936", "n" : "255", "nm" : "CESAR MAIA", "cc" : "DEM - DEM \/ PP \/ MDB \/ PTB \/ SOLIDARIEDADE \/ PSDB \/ PPS \/ PV \/ DC \/ PHS \/ AVANTE \/ PMN", "nv" : "ALICE TAMBORINDEGUY", "ns2" : "ALICE TAMBORINDEGUY", "nv" : "SERGIO ZVEITER", "ns1" : "SERGIO ZVEITER", "e" : "n", "v" : "2327634", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "17", "sqcand" : "190000615667", "n" : "290", "nm" : "FERNANDO FAGUNDES RIBEIRO", "cc" : "PCO", "nv" : "JOSE MARCIO TAVARES", "ns1" : "JOSE MARCIO TAVARES", "nv" : "CARLOS GUIDA", "ns2" : "CARLOS GUIDA", "e" : "n", "v" : "0", "vap" : "8816", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "12", "sqcand" : "190000602070", "n" : "211", "nm" : "MARTA BARÇANTE", "cc" : "PCB - PSOL \/ PCB", "nv" : "VALMIRIA GUIDA", "ns1" : "VALMIRIA GUIDA", "nv" : "RICARDO PINHEIRO", "ns2" : "RICARDO PINHEIRO", "e" : "n", "v" : "52734", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "190000607913", "n" : "555", "nm" : "AROLDE DE OLIVEIRA", "cc" : "PSD", "nv" : "RENATA GUERRA", "ns2" : "RENATA GUERRA", "nv" : "PORTINHO", "ns1" : "PORTINHO", "e" : "s", "v" : "2382265", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "190000614721", "n" : "177", "nm" : "FLÁVIO BOLSONARO", "cc" : "PSL", "nv" : "PAULO MARINHO", "ns1" : "PAULO MARINHO", "nv" : "LEONARDO RODRIGUES", "ns2" : "LEONARDO RODRIGUES", "e" : "s", "v" : "4380418", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "190000609940", "n" : "455", "nm" : "ASPASIA", "cc" : "PSDB - DEM \/ PP \/ MDB \/ PTB \/ SOLIDARIEDADE \/ PSDB \/ PPS \/ PV \/ DC \/ PHS \/ AVANTE \/ PMN", "nv" : "MARCO MAGALHÃES", "ns1" : "MARCO MAGALHÃES", "nv" : "JORGE RODINO", "ns2" : "JORGE RODINO", "e" : "n", "v" : "248868", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "190000626243", "n" : "281", "nm" : "MATTOS NASCIMENTO", "cc" : "PRTB", "nv" : "DJAMIM FERREIRA", "ns2" : "DJAMIM FERREIRA", "nv" : "FELIPE PEREIRA", "ns1" : "FELIPE PEREIRA", "e" : "n", "v" : "173968", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "190000613600", "n" : "131", "nm" : "LINDBERGH", "cc" : "PT - PT \/ PC do B", "nv" : "EDINHO ", "ns1" : "EDINHO ", "nv" : "ANAZIR", "ns2" : "ANAZIR", "e" : "n", "v" : "1419676", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }