
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "al", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "23:52:25", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "6387", "st" : "6387", "snt" : "0", "e" : "2187228", "ea" : "2187228", "ena" : "0", "c" : "1692875", "a" : "494353", "tv" : "3385750", "vb" : "245663", "vn" : "537603", "vp" : "0", "vv" : "2602484", "vl" : "0", "van" : "0", "vnom" : "2602484", "cand" : [ 
{ "seq" : "1", "sqcand" : "20000616686", "n" : "456", "nm" : "RODRIGO CUNHA", "cc" : "PSDB - PTC \/ PSDB \/ PP \/ PSB \/ PSC \/ PROS \/ PRB \/ DEM", "nv" : "HENRIQUE ARRUDA", "ns2" : "HENRIQUE ARRUDA", "nv" : "EUDÓCIA CALDAS", "ns1" : "EUDÓCIA CALDAS", "e" : "s", "v" : "895738", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "20000619789", "n" : "500", "nm" : "PROF. CICERO ALBUQUERQUE", "cc" : "PSOL - PSOL \/ PCB", "nv" : "NENEZA DOMINGOS", "ns2" : "NENEZA DOMINGOS", "nv" : "FELIPE CAVALCANTE", "ns1" : "FELIPE CAVALCANTE", "e" : "n", "v" : "57747", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "20000621740", "n" : "222", "nm" : "MAURICIO QUINTELLA", "cc" : "PR - MDB \/ PODE \/ PPS \/ PDT \/ PR \/ PTB \/ PHS \/ PV \/ PT \/ PRP \/ PRTB \/ PSD \/ DC \/ PC do B \/ AVANTE \/ SOLIDARIEDADE \/ PMN", "nv" : "GILVÂNIA BARROS", "ns2" : "GILVÂNIA BARROS", "nv" : "LUIZ ROMERO FARIAS", "ns1" : "LUIZ ROMERO FARIAS", "e" : "n", "v" : "494027", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "20000619794", "n" : "210", "nm" : "OSVALDO MACIEL", "cc" : "PCB - PSOL \/ PCB", "nv" : "INALDO VALOES", "ns1" : "INALDO VALOES", "nv" : "ANTONIO UGÁ", "ns2" : "ANTONIO UGÁ", "e" : "n", "v" : "14785", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "20000616900", "n" : "177", "nm" : "FLAVIO MORENO", "cc" : "PSL - PSL \/ PATRI \/ PPL", "nv" : "SARITA", "ns1" : "SARITA", "nv" : "MARCOS PERCIANO", "ns2" : "MARCOS PERCIANO", "e" : "n", "v" : "142757", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "20000621738", "n" : "151", "nm" : "RENAN", "cc" : "MDB - MDB \/ PODE \/ PPS \/ PDT \/ PR \/ PTB \/ PHS \/ PV \/ PT \/ PRP \/ PRTB \/ PSD \/ DC \/ PC do B \/ AVANTE \/ SOLIDARIEDADE \/ PMN", "nv" : "RAFAEL TENORIO", "ns1" : "RAFAEL TENORIO", "nv" : "SILVANIA BARBOSA", "ns2" : "SILVANIA BARBOSA", "e" : "s", "v" : "621562", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "20000616928", "n" : "511", "nm" : "SERGIO CABRAL", "cc" : "PATRI - PSL \/ PATRI \/ PPL", "nv" : "LUANA BORGES", "ns2" : "LUANA BORGES", "nv" : "JUNIOR MOREIRA", "ns1" : "JUNIOR MOREIRA", "e" : "n", "v" : "11552", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "20000616688", "n" : "111", "nm" : "BENEDITO DE LIRA", "cc" : "PP - PTC \/ PSDB \/ PP \/ PSB \/ PSC \/ PROS \/ PRB \/ DEM", "nv" : "LUIZ GUSTAVO DA SILVA LIMA", "ns2" : "LUIZ GUSTAVO DA SILVA LIMA", "nv" : "LUCIA TEOFILO", "ns1" : "LUCIA TEOFILO", "e" : "n", "v" : "364316", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "20000619178", "n" : "290", "nm" : "FLÁVIA MELO", "cc" : "PCO", "nv" : "NIL ANDRADE", "ns2" : "NIL ANDRADE", "nv" : "KÁTIA CAVALCANTE", "ns1" : "KÁTIA CAVALCANTE", "e" : "n", "v" : "0", "vap" : "6277", "dsit" : "Indeferido", "svnom" : "s" } ] }