
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "pr", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "22:37:22", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "26137", "st" : "26137", "snt" : "0", "e" : "7968409", "ea" : "7968409", "ena" : "0", "c" : "6616901", "a" : "1351508", "tv" : "13233802", "vb" : "1248770", "vn" : "1848095", "vp" : "0", "vv" : "10136937", "vl" : "0", "van" : "0", "vnom" : "10136937", "cand" : [ 
{ "seq" : "12", "sqcand" : "160000626117", "n" : "510", "nm" : "ROSELAINE BARROSO FERREIRA", "cc" : "PATRI - PSL \/ PTC \/ PATRI", "nv" : "HELENA SOUZA COSTA", "ns1" : "HELENA SOUZA COSTA", "nv" : "ROSI CONRADI", "ns2" : "ROSI CONRADI", "e" : "n", "v" : "49037", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "13", "sqcand" : "160000625767", "n" : "505", "nm" : "RODRIGO TOMAZINI", "cc" : "PSOL - PSOL \/ PCB", "nv" : "AUGUSTO LIMA", "ns1" : "AUGUSTO LIMA", "nv" : "LILIANA ARISTIDES", "ns2" : "LILIANA ARISTIDES", "e" : "n", "v" : "35233", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "160000621960", "n" : "151", "nm" : "REQUIÃO", "cc" : "MDB - MDB \/ PDT \/ SOLIDARIEDADE \/ PC do B", "nv" : "IRONDI PUGLIESI", "ns2" : "IRONDI PUGLIESI", "nv" : "LUIZ FERNANDO DELAZARI", "ns1" : "LUIZ FERNANDO DELAZARI", "e" : "n", "v" : "1528291", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "160000609983", "n" : "277", "nm" : "COMPADRE LUIZ ADÃO", "cc" : "DC - REDE \/ DC \/ PPL", "nv" : "LUZIA NORILER", "ns1" : "LUZIA NORILER", "nv" : "OSMAR GALVÃO", "ns2" : "OSMAR GALVÃO", "e" : "n", "v" : "87438", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "160000621503", "n" : "288", "nm" : "ZÉ BONI", "cc" : "PRTB - PRTB \/ PRP", "nv" : "GEONISIO MARINHO JR", "ns1" : "GEONISIO MARINHO JR", "nv" : "JAURI PRESTES", "ns2" : "JAURI PRESTES", "e" : "n", "v" : "264518", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "160000609967", "n" : "181", "nm" : "FLAVIO ARNS", "cc" : "REDE - REDE \/ DC \/ PPL", "nv" : "VILSON BASSO", "ns1" : "VILSON BASSO", "nv" : "FLAVIO VICENTE", "ns2" : "FLAVIO VICENTE", "e" : "s", "v" : "2331740", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "14", "sqcand" : "160000617073", "n" : "290", "nm" : "GILSON MEZAROBBA", "cc" : "PCO", "nv" : "ANTONIO GUARIZA", "ns2" : "ANTONIO GUARIZA", "nv" : "JOSÉ CARLOS TELLES", "ns1" : "JOSÉ CARLOS TELLES", "e" : "n", "v" : "10840", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "160000625760", "n" : "500", "nm" : "JACQUE PARMIGIANI", "cc" : "PSOL - PSOL \/ PCB", "nv" : "SÉRGIO FERREIRA DE SOUZA", "ns2" : "SÉRGIO FERREIRA DE SOUZA", "nv" : "PROFESSOR JOSE ODENIR", "ns1" : "PROFESSOR JOSE ODENIR", "e" : "n", "v" : "77450", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "160000622849", "n" : "456", "nm" : "BETO RICHA", "cc" : "PSDB - PP \/ PTB \/ DEM \/ PMN \/ PMB \/ PSB \/ PSDB \/ PROS", "nv" : "MARIA IRACLESIA", "ns2" : "MARIA IRACLESIA", "nv" : "NELSON PADOVANI", "ns1" : "NELSON PADOVANI", "e" : "n", "v" : "377872", "vap" : "0", "dsit" : "Pendente de julgamento", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "160000621567", "n" : "283", "nm" : "RODRIGO REIS", "cc" : "PRTB - PRTB \/ PRP", "nv" : "RAFAELA DE AGUIRRA PILAGALLO", "ns1" : "RAFAELA DE AGUIRRA PILAGALLO", "nv" : "JOSE ADÃO MONTEIRO", "ns2" : "JOSE ADÃO MONTEIRO", "e" : "n", "v" : "243353", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "160000622846", "n" : "144", "nm" : "ALEX CANZIANI", "cc" : "PTB - PP \/ PTB \/ DEM \/ PMN \/ PMB \/ PSB \/ PSDB \/ PROS", "nv" : "WALTER PETRUZZIELLO", "ns2" : "WALTER PETRUZZIELLO", "nv" : "LEONARDO DE MATTOS LEÃO", "ns1" : "LEONARDO DE MATTOS LEÃO", "e" : "n", "v" : "1304719", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "160000623011", "n" : "131", "nm" : "MIRIAN GONÇALVES", "cc" : "PT", "nv" : "JOÃOZINHO SANTANA", "ns2" : "JOÃOZINHO SANTANA", "nv" : "XIXO", "ns1" : "XIXO", "e" : "n", "v" : "599953", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "160000609227", "n" : "191", "nm" : "PROFESSOR ORIOVISTO GUIMARAES", "cc" : "PODE - PSD \/ PSC \/ PV \/ PR \/ PRB \/ PHS \/ PPS \/ PODE \/ AVANTE", "nv" : "PLINIO DESTRO", "ns2" : "PLINIO DESTRO", "nv" : "PAULO SALAMUNI", "ns1" : "PAULO SALAMUNI", "e" : "s", "v" : "2957239", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "160000621964", "n" : "123", "nm" : "NELTON", "cc" : "PDT - MDB \/ PDT \/ SOLIDARIEDADE \/ PC do B", "nv" : "TITO ZEGLIN", "ns1" : "TITO ZEGLIN", "nv" : "LAURENTINO BORSA", "ns2" : "LAURENTINO BORSA", "e" : "n", "v" : "269254", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }