
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "rn", "carper" : "5", "t" : "1", "f" : "o", "dt" : "07\/10\/2018", "ht" : "22:56:24", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "7389", "st" : "7389", "snt" : "0", "e" : "2372548", "ea" : "2372548", "ena" : "0", "c" : "1966450", "a" : "406098", "tv" : "3932900", "vb" : "264393", "vn" : "745686", "vp" : "0", "vv" : "2909592", "vl" : "0", "van" : "13229", "vnom" : "2909592", "cand" : [ 
{ "seq" : "5", "sqcand" : "200000610643", "n" : "199", "nm" : "JÁCOME", "cc" : "PODE - PDT \/ PP \/ MDB \/ PODE \/ DEM", "nv" : "JOELMO", "ns1" : "JOELMO", "nv" : "ALDA LEDA TAVEIRA", "ns2" : "ALDA LEDA TAVEIRA", "e" : "n", "v" : "307399", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "200000626720", "n" : "180", "nm" : "CAPITÃO STYVENSON", "cc" : "REDE", "nv" : "CORONEL MARGARIDA", "ns2" : "CORONEL MARGARIDA", "nv" : "ALISSON TAVEIRA", "ns1" : "ALISSON TAVEIRA", "e" : "s", "v" : "745827", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "200000611398", "n" : "456", "nm" : "GERALDO MELO", "cc" : "PSDB - PRB \/ PTB \/ PR \/ PPS \/ PMB \/ PTC \/ PSB \/ PRP \/ PSDB \/ PSD \/ AVANTE \/ PROS", "nv" : "EZEQUIEL FERREIRA", "ns1" : "EZEQUIEL FERREIRA", "nv" : "HAROLDO AZEVEDO", "ns2" : "HAROLDO AZEVEDO", "e" : "n", "v" : "382249", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "200000610644", "n" : "154", "nm" : "GARIBALDI FILHO", "cc" : "MDB - PDT \/ PP \/ MDB \/ PODE \/ DEM", "nv" : "DR BERNARDO", "ns2" : "DR BERNARDO", "nv" : "MARCELO QUEIROZ", "ns1" : "MARCELO QUEIROZ", "e" : "n", "v" : "376199", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "200000611620", "n" : "161", "nm" : "ANA CELIA", "cc" : "PSTU", "nv" : "NAZARENO GODEIRO", "ns2" : "NAZARENO GODEIRO", "nv" : "CHERLINTON SARAIVA", "ns1" : "CHERLINTON SARAIVA", "e" : "n", "v" : "8233", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "200000602579", "n" : "277", "nm" : "DR JOANILSON", "cc" : "DC - SOLIDARIEDADE \/ PV \/ DC \/ PSC \/ PSL \/ PATRI", "nv" : "DOUGLAS AZEVEDO", "ns1" : "DOUGLAS AZEVEDO", "nv" : "PROF JOSUE MOREIRA", "ns2" : "PROF JOSUE MOREIRA", "e" : "n", "v" : "15418", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "12", "sqcand" : "200000601386", "n" : "500", "nm" : "PROFESSOR LAILSON", "cc" : "PSOL", "nv" : "GERLANE MELO", "ns1" : "GERLANE MELO", "nv" : "IRMÃO WALMIR", "ns2" : "IRMÃO WALMIR", "e" : "n", "v" : "7420", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "200000606729", "n" : "313", "nm" : "DRª ZENAIDE MAIA", "cc" : "PHS - PT \/ PC do B \/ PHS", "nv" : "PASTOR MANOEL ROBERTO", "ns2" : "PASTOR MANOEL ROBERTO", "nv" : "JÚNIOR SOUTO", "ns1" : "JÚNIOR SOUTO", "e" : "s", "v" : "660315", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "15", "sqcand" : "200000623083", "n" : "288", "nm" : "JURANDIR MARINHO", "cc" : "PRTB", "nv" : "FRANCISCA SOUZA", "ns1" : "FRANCISCA SOUZA", "nv" : "ANTONIO LOPES", "ns2" : "ANTONIO LOPES", "e" : "n", "v" : "0", "vap" : "13229", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "6", "sqcand" : "200000606724", "n" : "131", "nm" : "ALEXANDRE MOTTA", "cc" : "PT - PT \/ PC do B \/ PHS", "nv" : "JANA SA", "ns1" : "JANA SA", "nv" : "JAILSON MORAIS", "ns2" : "JAILSON MORAIS", "e" : "n", "v" : "242465", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "200000602577", "n" : "777", "nm" : "MAGNÓLIA", "cc" : "SOLIDARIEDADE - SOLIDARIEDADE \/ PV \/ DC \/ PSC \/ PSL \/ PATRI", "nv" : "RICARDO CAXANGÁ", "ns1" : "RICARDO CAXANGÁ", "nv" : "RIVALDO FERNANDES", "ns2" : "RIVALDO FERNANDES", "e" : "n", "v" : "114055", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "14", "sqcand" : "200000611622", "n" : "169", "nm" : "JOÃO MORAIS ", "cc" : "PSTU", "nv" : "EDINEIDE PAIVA", "ns2" : "EDINEIDE PAIVA", "nv" : "REJANE RODRIGUES ", "ns1" : "REJANE RODRIGUES ", "e" : "n", "v" : "4291", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "200000601385", "n" : "502", "nm" : "TELMA GURGEL", "cc" : "PSOL", "nv" : "PROF TITA HOLANDA", "ns2" : "PROF TITA HOLANDA", "nv" : "SANTINO ARRUDA", "ns1" : "SANTINO ARRUDA", "e" : "n", "v" : "23846", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "200000623084", "n" : "282", "nm" : "LEVI COSTA", "cc" : "PRTB", "nv" : "GERACINA", "ns2" : "GERACINA", "nv" : "WELDONS PEREIRA", "ns1" : "WELDONS PEREIRA", "e" : "n", "v" : "14709", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "13", "sqcand" : "200000627396", "n" : "188", "nm" : "NAPOLEÃO", "cc" : "REDE", "nv" : "MACIEL", "ns1" : "MACIEL", "nv" : "CIBELLE MARQUES", "ns2" : "CIBELLE MARQUES", "e" : "n", "v" : "7166", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }