
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "ma", "carper" : "5", "t" : "1", "f" : "o", "dt" : "08\/10\/2018", "ht" : "03:37:04", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "15830", "st" : "15830", "snt" : "0", "e" : "4536193", "ea" : "4536193", "ena" : "0", "c" : "3604582", "a" : "931611", "tv" : "7209164", "vb" : "565180", "vn" : "939985", "vp" : "0", "vv" : "5703999", "vl" : "0", "van" : "0", "vnom" : "5703999", "cand" : [ 
{ "seq" : "5", "sqcand" : "100000613999", "n" : "170", "nm" : "SAMOEL DE ITAPECURU", "cc" : "PSL - PSL \/ PRTB", "nv" : "JOÃO DO GIGANTÃO", "ns2" : "JOÃO DO GIGANTÃO", "nv" : "ELIAS MARÇAL ", "ns1" : "ELIAS MARÇAL ", "e" : "n", "v" : "254979", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "100000618769", "n" : "212", "nm" : "IÊGO BRUNNO", "cc" : "PCB - PSOL \/ PCB", "nv" : "ZE JK", "ns2" : "ZE JK", "nv" : "JOAB LOBATO", "ns1" : "JOAB LOBATO", "e" : "n", "v" : "23327", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "100000603920", "n" : "123", "nm" : "WEVERTON", "cc" : "PDT - PC do B \/ PRB \/ PDT \/ PPS \/ DEM \/ PSB \/ PR \/ PP \/ PROS \/ PT \/ PTB \/ PATRI \/ PTC \/ SOLIDARIEDADE \/ PPL \/ AVANTE", "nv" : "ROBERTH BRINGEL", "ns1" : "ROBERTH BRINGEL", "nv" : "SUELY PEREIRA", "ns2" : "SUELY PEREIRA", "e" : "s", "v" : "1997443", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "100000612587", "n" : "456", "nm" : "ALEXANDRE ALMEIDA", "cc" : "PSDB - PODE \/ REDE \/ DC \/ PHS \/ PMN \/ PSDB", "nv" : "MIRIAM RIBEIRO", "ns2" : "MIRIAM RIBEIRO", "nv" : "SERGIO MENDES", "ns1" : "SERGIO MENDES", "e" : "n", "v" : "191997", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "6", "sqcand" : "100000612585", "n" : "455", "nm" : "ZÉ REINALDO", "cc" : "PSDB - PODE \/ REDE \/ DC \/ PHS \/ PMN \/ PSDB", "nv" : "MARCIO ENDLES", "ns2" : "MARCIO ENDLES", "nv" : "LUCYANA GENESIO", "ns1" : "LUCYANA GENESIO", "e" : "n", "v" : "219225", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "100000602468", "n" : "163", "nm" : "PRETA LU", "cc" : "PSTU", "nv" : "BETO BELO", "ns2" : "BETO BELO", "nv" : "WILSON LEITE", "ns1" : "WILSON LEITE", "e" : "n", "v" : "47407", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "100000602467", "n" : "161", "nm" : "SAULO ARCANGELI", "cc" : "PSTU", "nv" : "IRISNETE GALENO", "ns2" : "IRISNETE GALENO", "nv" : "ESTER DURANS", "ns1" : "ESTER DURANS", "e" : "n", "v" : "36436", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "100000603923", "n" : "232", "nm" : "ELIZIANE GAMA", "cc" : "PPS - PC do B \/ PRB \/ PDT \/ PPS \/ DEM \/ PSB \/ PR \/ PP \/ PROS \/ PT \/ PTB \/ PATRI \/ PTC \/ SOLIDARIEDADE \/ PPL \/ AVANTE", "nv" : "PEDRO FERNANDES", "ns1" : "PEDRO FERNANDES", "nv" : "DR. BENE CAMACHO", "ns2" : "DR. BENE CAMACHO", "e" : "s", "v" : "1539916", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "100000608136", "n" : "150", "nm" : "EDISON LOBÃO", "cc" : "MDB - MDB \/ PV \/ PSD \/ PSC \/ PMB \/ PRP", "nv" : "ANTONIO LEITE", "ns2" : "ANTONIO LEITE", "nv" : "LOBÃO FILHO", "ns1" : "LOBÃO FILHO", "e" : "n", "v" : "553276", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "8", "sqcand" : "100000618783", "n" : "500", "nm" : "SAULO PINTO", "cc" : "PSOL - PSOL \/ PCB", "nv" : "KEPLER RIBEIRO", "ns1" : "KEPLER RIBEIRO", "nv" : "ROSÁRIO PROFESSORA", "ns2" : "ROSÁRIO PROFESSORA", "e" : "n", "v" : "87100", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "100000608138", "n" : "432", "nm" : "SARNEY FILHO", "cc" : "PV - MDB \/ PV \/ PSD \/ PSC \/ PMB \/ PRP", "nv" : "JOÃO MANOEL", "ns2" : "JOÃO MANOEL", "nv" : "CLOVIS FECURY", "ns1" : "CLOVIS FECURY", "e" : "n", "v" : "752893", "vap" : "0", "dsit" : "Deferido com recurso", "svnom" : "n" } ] }