
{ "ele" : "297", "tpabr" : "uf", "cdabr" : "rr", "carper" : "5", "t" : "1", "f" : "o", "dt" : "10\/10\/2018", "ht" : "10:17:56", "dv" : "s", "tf" : "s", "v" : "2", "esae" : "n", "mnae" : "", "s" : "1172", "st" : "1172", "snt" : "0", "e" : "333153", "ea" : "333153", "ena" : "0", "c" : "286754", "a" : "46399", "tv" : "573508", "vb" : "21366", "vn" : "46066", "vp" : "0", "vv" : "495575", "vl" : "0", "van" : "10501", "vnom" : "495575", "cand" : [ 
{ "seq" : "8", "sqcand" : "230000614196", "n" : "212", "nm" : "TELMA TAUREPANG", "cc" : "PCB - PCB \/ PSOL \/ PSTU", "nv" : "RAPHAEL UCHÔA", "ns2" : "RAPHAEL UCHÔA", "nv" : "PROFESSOR MISAQUE", "ns1" : "PROFESSOR MISAQUE", "e" : "n", "v" : "13839", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "1", "sqcand" : "230000601673", "n" : "255", "nm" : "CHICO RODRIGUES", "cc" : "DEM - PSDB \/ DEM \/ MDB \/ PSD \/ PPS \/ SOLIDARIEDADE \/ DC", "nv" : "PEDRO ARTHUR", "ns1" : "PEDRO ARTHUR", "nv" : "ONÉSIMO CRUZ", "ns2" : "ONÉSIMO CRUZ", "e" : "s", "v" : "111466", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "7", "sqcand" : "230000615947", "n" : "144", "nm" : "JÚLIO MARTINS", "cc" : "PTB - PTB \/ PV \/ REDE \/ PT", "nv" : "LEOMA FERREIRA", "ns2" : "LEOMA FERREIRA", "nv" : "ROGÉRIO MIRANDA", "ns1" : "ROGÉRIO MIRANDA", "e" : "n", "v" : "20004", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "11", "sqcand" : "230000601471", "n" : "512", "nm" : "CHRISTIAN SANTOS", "cc" : "PATRI", "nv" : "HELTON SOUZA", "ns1" : "HELTON SOUZA", "nv" : "ANGELO DO CANTÁ", "ns2" : "ANGELO DO CANTÁ", "e" : "n", "v" : "0", "vap" : "10501", "dsit" : "Indeferido com recurso", "svnom" : "s" }, 
{ "seq" : "6", "sqcand" : "230000609417", "n" : "177", "nm" : "PR.ISAMAR RAMALHO", "cc" : "PSL - PSL \/ PRB \/ PTC \/ PRP \/ PROS \/ PSC \/ PPL \/ PATRI**", "nv" : "FRANCISCO IRANEUDO ALVES", "ns1" : "FRANCISCO IRANEUDO ALVES", "nv" : "KELTON LOPES", "ns2" : "KELTON LOPES", "e" : "n", "v" : "52028", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "3", "sqcand" : "230000601676", "n" : "156", "nm" : "ROMERO JUCÁ", "cc" : "MDB - PSDB \/ DEM \/ MDB \/ PSD \/ PPS \/ SOLIDARIEDADE \/ DC", "nv" : "SÉRGIO PILLON", "ns1" : "SÉRGIO PILLON", "nv" : "SANDER SALOMÃO", "ns2" : "SANDER SALOMÃO", "e" : "n", "v" : "84940", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "10", "sqcand" : "230000614179", "n" : "161", "nm" : "LOURIVAL", "cc" : "PSTU - PCB \/ PSOL \/ PSTU", "nv" : "CLEIDIANO", "ns2" : "CLEIDIANO", "nv" : "ZÉ LIMA", "ns1" : "ZÉ LIMA", "e" : "n", "v" : "1866", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "2", "sqcand" : "230000609420", "n" : "107", "nm" : "MECIAS DE JESUS", "cc" : "PRB - PSL \/ PRB \/ PTC \/ PRP \/ PROS \/ PSC \/ PPL \/ PATRI**", "nv" : "ENFERMEIRA ROBERTA", "ns1" : "ENFERMEIRA ROBERTA", "nv" : "AFONSO PARENTE", "ns2" : "AFONSO PARENTE", "e" : "s", "v" : "85366", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "9", "sqcand" : "230000615949", "n" : "434", "nm" : "RUDSON LEITE", "cc" : "PV - PTB \/ PV \/ REDE \/ PT", "nv" : "VANÚBIA PRAXEDES", "ns2" : "VANÚBIA PRAXEDES", "nv" : "BARTÔ PATAMONA", "ns1" : "BARTÔ PATAMONA", "e" : "n", "v" : "5755", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "5", "sqcand" : "230000614386", "n" : "222", "nm" : "LUCIANO CASTRO", "cc" : "PR - PP \/ PDT \/ PODE \/ PRTB \/ PR \/ PHS \/ PC do B", "nv" : "TUTI LOPES", "ns1" : "TUTI LOPES", "nv" : "IRMÃ GRAÇA", "ns2" : "IRMÃ GRAÇA", "e" : "n", "v" : "56147", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" }, 
{ "seq" : "4", "sqcand" : "230000614388", "n" : "123", "nm" : "ANGELA PORTELA", "cc" : "PDT - PP \/ PDT \/ PODE \/ PRTB \/ PR \/ PHS \/ PC do B", "nv" : "AUGUSTO IGLESIAS", "ns2" : "AUGUSTO IGLESIAS", "nv" : "WALACE", "ns1" : "WALACE", "e" : "n", "v" : "64164", "vap" : "0", "dsit" : "Deferido", "svnom" : "n" } ] }